/* =========================================================================
   LinkedIn post-engagement data for the Continia competitor dashboard.
   Public engagement on each company's recent posts (reactions / comments /
   reposts). Totals + averages are computed in dashboard.js from these raw
   posts, so the comparison table can never drift from the source.

   Source: Assets/linkedin_posts_report_Jul 10.txt (captured 2026-07-10).
   "t" is the post title (first line of the post, normalized to plain ASCII),
   "ty" is the content type pill. The report lists newest-first per company;
   we keep the full window (up to 30 recent posts each).

   On the tracking list but deliberately excluded (watch, not card - see
   FULL-UPDATE.md): incedo-inc (consulting firm), signup-software (Truvio's
   former brand, already the ExFlow/Truvio card), stripe (payments benchmark).
   ========================================================================= */

window.LI_DATA = {
  source: "LinkedIn public engagement",
  captured: "2026-07-10",
  windowLabel: "up to 30 recent posts each · public engagement",
  companies: [
    { name: "Continia Software", ours: true, posts: [
      {t:"See Continia in action, at your own pace", ty:"Image", r:34, c:1, rp:4},
      {t:"It's about time", ty:"Carousel", r:59, c:1, rp:0},
      {t:"Fake invoices don't always look fake", ty:"Image", r:22, c:0, rp:2},
      {t:"Our biggest team meetup yet - our entire global team together", ty:"Carousel", r:233, c:4, rp:6},
      {t:"From a full-time AP person to automation in minutes", ty:"Image", r:22, c:0, rp:3},
      {t:"The Elevate tour continues - this time in Poland", ty:"Carousel", r:71, c:1, rp:0},
      {t:"Kicking off Continia Elevate in the UK", ty:"Video", r:53, c:2, rp:1},
      {t:"We're ISO 27001 certified", ty:"Carousel", r:196, c:2, rp:1},
      {t:"It's about time ... we cycled to work (May commute)", ty:"Carousel", r:69, c:1, rp:0},
      {t:"Continia is growing - swipe to find your next role", ty:"Document/carousel", r:42, c:0, rp:0},
      {t:"Your BC setup is almost there", ty:"Video", r:34, c:0, rp:4},
      {t:"Continia Elevate comes to Warsaw", ty:"Image", r:47, c:4, rp:2},
      {t:"That's a wrap on Directions ASIA", ty:"Carousel", r:59, c:0, rp:0},
      {t:"The Continia Expense App now supports Microsoft integration", ty:"Image", r:69, c:0, rp:2},
      {t:"Is your Accounts Receivable setup as efficient as it could be", ty:"Document/carousel", r:39, c:0, rp:0},
      {t:"Celebrating our very own Microsoft MVP", ty:"Carousel", r:217, c:17, rp:1},
      {t:"Catch up on 2026 R1 and showcase your expertise", ty:"Image", r:27, c:0, rp:2},
      {t:"Let's catch up at DynamicsMinds", ty:"Image", r:66, c:1, rp:1},
      {t:"Did you miss our 2026 R1 'What's New' webinars", ty:"Image", r:31, c:0, rp:1},
      {t:"25 ars samarbejde og +500 aktive Continia-losninger", ty:"Carousel", r:75, c:2, rp:2},
      {t:"Celebrating the first release of 2026 - 2026 R1 is live", ty:"Carousel", r:80, c:0, rp:1},
      {t:"2026 R1: A big step forward for AR automation", ty:"Video", r:84, c:2, rp:6},
      {t:"Hopping into Easter - a little Easter surprise", ty:"Carousel", r:61, c:0, rp:2},
      {t:"Handling 15,000 invoices every month is no small task", ty:"Image", r:27, c:0, rp:1},
      {t:"Join us at Days of Knowledge Nordic", ty:"Image", r:33, c:0, rp:1},
      {t:"Happy birthday to our CEO", ty:"Carousel", r:208, c:20, rp:0},
      {t:"Get a first look at 2026 R1", ty:"Document/carousel", r:31, c:0, rp:3},
      {t:"Vi fejrer +500 implementerede Continia-losninger", ty:"Carousel", r:77, c:0, rp:3},
      {t:"Where to meet Continia this spring and summer", ty:"Document/carousel", r:34, c:0, rp:3},
      {t:"Lap times (almost) as quick as our invoice process", ty:"Carousel", r:53, c:0, rp:1}
    ]},
    { name: "Truvio", posts: [
      {t:"Better fraud detection starts with better visibility", ty:"Image", r:5, c:0, rp:1},
      {t:"Is your approval process keeping your finance team working", ty:"Text", r:10, c:0, rp:2},
      {t:"Traditional AP automation requires companies to define every invoice scenario upfront", ty:"Image", r:15, c:0, rp:3},
      {t:"AI adoption in B2B eCommerce moved faster than expected - 70% of companies", ty:"Image", r:16, c:0, rp:2},
      {t:"Is your ERP helping your business scale", ty:"Text", r:15, c:1, rp:0},
      {t:"Does summer seem to expose every bottleneck in your finance operations", ty:"Image", r:28, c:0, rp:11},
      {t:"Join us for our next Commerce Product Brief on the 26th of August", ty:"Image", r:14, c:0, rp:1},
      {t:"This September, our Commerce partner community comes together in Aarhus", ty:"Image", r:23, c:0, rp:4},
      {t:"3 products (Truvio suite)", ty:"Video", r:24, c:0, rp:3},
      {t:"Going live with AP automation is an important step forward", ty:"Video", r:21, c:0, rp:5},
      {t:"On Thursday, we're talking about what AI really needs from your product data", ty:"Image", r:23, c:0, rp:1},
      {t:"When evaluating AP automation solutions, Sinclar Group Forest Products Ltd", ty:"Image", r:18, c:1, rp:3},
      {t:"Your catalogue has 400 products missing SEO descriptions", ty:"Image", r:22, c:1, rp:2},
      {t:"Truvio Commerce Customer Day 2026 in motion", ty:"Video", r:51, c:2, rp:3},
      {t:"When evaluating AP automation, AURA Energi didn't just listen to sales pitches", ty:"Image", r:24, c:0, rp:6},
      {t:"AI can only work with the product data you give it", ty:"Image", r:30, c:1, rp:7},
      {t:"The program for Truvio Commerce Partner Days 2026 is now live", ty:"Video", r:17, c:1, rp:9},
      {t:"Last week we attended Forretning Online in Aarhus - a full-day conference", ty:"Carousel", r:32, c:2, rp:3},
      {t:"Fraud risk is hiding in everyday finance workflows - emailed invoices, manual entry", ty:"Text", r:13, c:0, rp:2},
      {t:"I dag er Truvio med til Forretning Online hos Novicell i Aarhus - over 500 deltagere", ty:"Image", r:49, c:1, rp:1},
      {t:"What does successful B2B eCommerce look like today", ty:"Image", r:17, c:1, rp:5},
      {t:"Truvio is heading to Toronto - Dynamics Regional event on June 18-19", ty:"Image", r:35, c:0, rp:2},
      {t:"Driving scalable AP automation across a multi-entity forestry business (Sinclar Group)", ty:"Image", r:16, c:0, rp:4},
      {t:"Last chance", ty:"Video", r:8, c:0, rp:0},
      {t:"AI is changing the way customers discover products", ty:"Image", r:17, c:2, rp:3},
      {t:"We are excited to attend the Community Summit NA Roadshow in Charlotte, June 9", ty:"Image", r:20, c:0, rp:2},
      {t:"88% of surveyed manufacturers and wholesalers now sell online", ty:"Image", r:24, c:0, rp:5},
      {t:"What if managing commerce data could start with a simple question", ty:"Image", r:35, c:0, rp:6},
      {t:"More than half of B2B revenue now comes from online orders", ty:"Image", r:23, c:0, rp:5},
      {t:"The numbers don't lie - B2B eCommerce is reshaping manufacturers and distributors", ty:"Text", r:16, c:0, rp:6}
    ]},
    { name: "Equisys", posts: [
      {t:"With Zetadocs, drag and drop supporting documents against a journal entry in BC", ty:"Image", r:2, c:0, rp:2},
      {t:"Missed our recent webinar? Catch up now", ty:"Video", r:4, c:0, rp:2},
      {t:"A few hours away from our webinar 'Discover THE BEST AP Automation for Business Central'", ty:"Image", r:0, c:0, rp:1},
      {t:"Less than 24 hours left to register for our webinar", ty:"Image", r:2, c:0, rp:3},
      {t:"Looking for a smarter way to manage employee expenses and ensure compliant claims", ty:"Image", r:3, c:0, rp:3},
      {t:"A great time sponsoring Directions North America 2026", ty:"Carousel", r:12, c:0, rp:2},
      {t:"An amazing first day at Directions North America", ty:"Image", r:14, c:0, rp:5},
      {t:"We'll be in Orlando, Florida next week for Directions North America", ty:"Image", r:5, c:0, rp:3},
      {t:"Headed to Directions in Orlando in 2 weeks - Booth E-32", ty:"Image", r:6, c:0, rp:4},
      {t:"Deliver smarter, not harder (Zetadocs Delivery)", ty:"Image", r:2, c:0, rp:0},
      {t:"Looking for an expense management solution built for Business Central", ty:"Image", r:7, c:0, rp:2},
      {t:"Even the most well-written expense policies can be difficult to enforce", ty:"Image", r:7, c:0, rp:4},
      {t:"See how Zetadocs can transform the way you work", ty:"Image", r:6, c:0, rp:4},
      {t:"The future of accounts payable is automated", ty:"Article/Link", r:2, c:0, rp:0},
      {t:"Accounting teams in manufacturing (and beyond) face challenges with manual processes", ty:"Article/Link", r:1, c:0, rp:0},
      {t:"Thank you to all who stopped by our booth at Directions EMEA 2025", ty:"Image", r:11, c:0, rp:2},
      {t:"Our team is enjoying the sessions and conversations at Directions", ty:"Image", r:1, c:0, rp:0},
      {t:"We're delighted to be at Directions EMEA 2025 in Poznan", ty:"Image", r:22, c:0, rp:5},
      {t:"Zetadocs Expenses provides a powerful solution that's simple to manage", ty:"Image", r:3, c:0, rp:2},
      {t:"Zetadocs Delivery helps businesses reduce document delivery costs", ty:"Image", r:3, c:0, rp:3},
      {t:"AI adoption in the UK is booming, especially in finance and accounting", ty:"Article/Link", r:2, c:0, rp:1},
      {t:"With reporting from Zetadocs Expenses, your finance team gets real-time insight", ty:"Image", r:0, c:0, rp:0},
      {t:"How does OCR work in AP automation, and why is it so important", ty:"Article/Link", r:0, c:0, rp:1},
      {t:"Recently, the team got together in London for our company-wide meet up", ty:"Carousel", r:5, c:0, rp:0},
      {t:"Don't miss out", ty:"Image", r:1, c:0, rp:0},
      {t:"What is the Zetadocs FactBox and how does it work", ty:"Video", r:3, c:0, rp:1},
      {t:"Read our latest whitepaper on the hidden costs often overlooked", ty:"Image", r:5, c:0, rp:2}
    ]},
    { name: "Medius", posts: [
      {t:"The most significant financial leaks in transportation rarely appear on the invoice header", ty:"Image", r:7, c:0, rp:0},
      {t:"Late payments affect most businesses, even those using e-invoicing", ty:"Image", r:10, c:0, rp:2},
      {t:"Is your payment mix actually working for you - or against you", ty:"Image", r:11, c:0, rp:2},
      {t:"Finance and diplomacy have more in common than you'd think", ty:"Carousel", r:120, c:1, rp:7},
      {t:"Nobody goes into a finance role thinking 'I can't wait to manage late payments'", ty:"Image", r:12, c:0, rp:1},
      {t:"Thorlux Lighting's journey to AP excellence - from manual bottlenecks to efficiency", ty:"Image", r:29, c:0, rp:4},
      {t:"Manual exception handling", ty:"Image", r:24, c:1, rp:2},
      {t:"If July gives you a little breathing room, why not learn something new about AP", ty:"Document/carousel", r:9, c:0, rp:1},
      {t:"Many legacy AP systems weren't built for the complexity of freight charges", ty:"Image", r:21, c:0, rp:3},
      {t:"A new edition of MediusExplains", ty:"Document/carousel", r:8, c:0, rp:1},
      {t:"E-invoicing is no longer just a compliance checkbox - it's becoming a competitive edge", ty:"Image", r:11, c:0, rp:5},
      {t:"Looking forward to this", ty:"Image", r:25, c:0, rp:5},
      {t:"Garment manufacturing doesn't slow down for admin", ty:"Image", r:15, c:0, rp:0},
      {t:"How is AI revolutionizing manufacturing AP processes", ty:"Image", r:14, c:0, rp:2},
      {t:"Medius has reached 30,000 LinkedIn followers", ty:"Image", r:76, c:0, rp:0},
      {t:"Three days", ty:"Carousel", r:69, c:7, rp:0},
      {t:"An amazing day 1 at the Gartner Finance Symposium/Xpo 2026", ty:"Carousel", r:108, c:0, rp:5},
      {t:"This isn't a product announcement", ty:"Image", r:72, c:0, rp:8},
      {t:"As a gold sponsor of DynamicsMinds 2026, the Medius team will be in Portoroz, Slovenia", ty:"Image", r:37, c:3, rp:1},
      {t:"We earned four Customer Value distinction honors in The Hackett Group", ty:"Image", r:25, c:0, rp:3},
      {t:"Meet us at the Gartner Finance Symposium & Xpo in the UK this June", ty:"Image", r:19, c:1, rp:3},
      {t:"E-invoicing is no longer just a compliance initiative", ty:"Image", r:43, c:2, rp:9},
      {t:"The average non-PO invoice takes 7 days", ty:"Image", r:42, c:0, rp:6},
      {t:"The global shift to e-invoicing: are you ready", ty:"Document/carousel", r:13, c:1, rp:4},
      {t:"If fraud prevention and supplier headaches are on your radar, this one's worth a lunch break", ty:"Image", r:10, c:0, rp:1},
      {t:"In construction, slow AP processes are a bottleneck", ty:"Document/carousel", r:12, c:0, rp:4},
      {t:"Four things AP automation handles that your ERP was never designed for", ty:"Image", r:39, c:4, rp:8},
      {t:"Rapid growth in logistics masks rising operational complexity", ty:"Document/carousel", r:16, c:1, rp:2},
      {t:"Yesterday in Utrecht, Medius hosted its very first CFO Circle Benelux", ty:"Video", r:76, c:4, rp:7},
      {t:"Good accounts payable management isn't an afterthought in retail", ty:"Image", r:27, c:0, rp:0}
    ]},
    { name: "Qvalia", posts: [
      {t:"E-invoicing mandates are becoming infrastructure decisions", ty:"Image", r:3, c:0, rp:0},
      {t:"The new Billentis report on the global e-invoicing market is here", ty:"Image", r:6, c:1, rp:0},
      {t:"Slovakia's eFaktura framework is another step in Europe's transition to structured invoicing", ty:"Image", r:26, c:0, rp:2},
      {t:"Qvalia is now certified for Slovakia e-invoicing under the eFaktura framework", ty:"Image", r:31, c:1, rp:6},
      {t:"Qvalia's Business Continuity Management System certified against ISO 22301", ty:"Image", r:6, c:0, rp:1},
      {t:"Qvalia is now listed in the Cloud Security Alliance STAR Registry", ty:"Image", r:8, c:1, rp:0},
      {t:"Qvalia is now available on iPhone and Android", ty:"Image", r:42, c:5, rp:5},
      {t:"In 2025, we expanded Qvalia's platform across nearly all fronts", ty:"Image", r:13, c:1, rp:2},
      {t:"[Peppol for developers] How to get started with Peppol API", ty:"Image", r:9, c:0, rp:1},
      {t:"Belgium mandates Peppol e-invoicing for most B2B transactions on January 1, 2026", ty:"Image", r:9, c:0, rp:1},
      {t:"A timeline of finance tech: from 1940s credit scoring to modern ML", ty:"Carousel", r:7, c:0, rp:0},
      {t:"Few areas are better positioned to gain more from the AI revolution than finance", ty:"Image", r:5, c:0, rp:0},
      {t:"Summer reading no 4: The definitive guide to Peppol", ty:"Document/carousel", r:7, c:0, rp:0},
      {t:"Summer reading no 3: Peppol e-orders - how it works & how to get started", ty:"Document/carousel", r:12, c:0, rp:2}
    ]},
    { name: "AMC Banking", posts: [
      {t:"Before summer kicks off - a small milestone from AMC Banking (own SWIFT BIC)", ty:"Image", r:11, c:1, rp:2},
      {t:"Your biggest compliance risk might be a process nobody questions anymore", ty:"Article/Link", r:6, c:0, rp:2},
      {t:"Thanks to everybody who showed up for the reception in our new building", ty:"Carousel", r:29, c:1, rp:0},
      {t:"You can still register for our reception next week", ty:"Text", r:0, c:0, rp:0},
      {t:"AMC Banking operates under Service Provider Agreements with selected banks", ty:"Text", r:9, c:0, rp:0},
      {t:"AMC is expanding - we are currently looking for a Java developer", ty:"Article/Link", r:12, c:0, rp:3},
      {t:"Still uploading payment files manually?", ty:"Article/Link", r:6, c:0, rp:0},
      {t:"We're moving and we'd love to celebrate with you", ty:"Text", r:12, c:0, rp:1},
      {t:"The torch has officially been passed - moving into Kobenhavns Frikirke", ty:"Image", r:56, c:4, rp:1},
      {t:"Enterprise treasury demands structure, visibility, and control", ty:"Image", r:7, c:0, rp:0},
      {t:"You can still sign up for our webinar tomorrow (treasury deep dive)", ty:"Article/Link", r:4, c:0, rp:0},
      {t:"How AMC Banking's intelligent cash sweeping works for Microsoft Dynamics", ty:"Video", r:11, c:0, rp:0},
      {t:"In case you haven't signed up for our treasury extension webinar on cash sweeping", ty:"Article/Link", r:5, c:0, rp:0},
      {t:"We're excited to team up with Columbus to show how liquidity management can be automated", ty:"Image", r:6, c:0, rp:2},
      {t:"Convenience is the key word for our AMC Banking app", ty:"Text", r:8, c:0, rp:0},
      {t:"We've got two seats open at AMC Banking - a Finance & Operations Developer and more", ty:"Text", r:9, c:0, rp:0}
    ]},
    { name: "B2Brouter", posts: [
      {t:"La reforme de la facturation electronique en France ne se limite pas au choix d'une plateforme", ty:"Article/Link", r:0, c:0, rp:0},
      {t:"Do you have clients, suppliers or subsidiaries in Germany?", ty:"Document/carousel", r:3, c:0, rp:0},
      {t:"La solucion publica de facturacion electronica de la AEAT", ty:"Document/carousel", r:7, c:1, rp:0},
      {t:"France's e-invoicing reform is not just about sending invoices (via Capde)", ty:"Image", r:2, c:0, rp:1},
      {t:"La facturation electronique arrive en France", ty:"Article/Link", r:5, c:0, rp:1},
      {t:"Proximos webinars | Julio 2026", ty:"Image", r:1, c:0, rp:1},
      {t:"Upcoming webinars | July 2026", ty:"Image", r:1, c:0, rp:0},
      {t:"Empfangen ist nicht gleich Verarbeiten (DE)", ty:"Document/carousel", r:3, c:0, rp:0},
      {t:"Tu tienda online no puede permitirse facturar 'a mano' (ES)", ty:"Image", r:11, c:0, rp:3},
      {t:"We're excited to announce our partnership with B2Brouter", ty:"Document/carousel", r:28, c:2, rp:7},
      {t:"La factura electronica obligatoria ya tiene marco regulatorio (ES)", ty:"Article/Link", r:5, c:0, rp:0},
      {t:"Electronic invoicing is no longer just about tax compliance, it's about data liquidity", ty:"Document/carousel", r:5, c:0, rp:1},
      {t:"B2Brouter attended Peppol Conference Europe 2026 in Brussels", ty:"Carousel", r:15, c:0, rp:2},
      {t:"Eine E-Rechnung zu empfangen bedeutet nicht, sie auch zu verarbeiten (DE)", ty:"Text", r:2, c:0, rp:1},
      {t:"B2Brouter shares a day with partners at ERP Summit Espana", ty:"Image", r:40, c:0, rp:2},
      {t:"Crees que Ley Crea y Crece y VeriFactu son lo mismo? (ES)", ty:"Document/carousel", r:8, c:0, rp:1},
      {t:"In 8 days, B2Brouter will attend Peppol Conference Europe 2026 in Brussels", ty:"Text", r:5, c:0, rp:2},
      {t:"Great reflection from Henrik Moller on a topic often overlooked in e-invoicing", ty:"Text", r:1, c:0, rp:0},
      {t:"Upcoming webinars | June 2026", ty:"Image", r:8, c:0, rp:2},
      {t:"Manana hablaremos sobre la Ley Crea y Crece y la nueva facturacion electronica (ES)", ty:"Image", r:3, c:0, rp:0},
      {t:"Compliance gets companies through the door, but interoperability defines the future", ty:"Text", r:10, c:0, rp:1},
      {t:"La facturation electronique, un levier de simplification pour les PME francaises", ty:"Document/carousel", r:4, c:0, rp:1},
      {t:"Choisir sa Plateforme Agreee ne devrait pas se faire dans l'urgence (FR)", ty:"Document/carousel", r:10, c:2, rp:2},
      {t:"Tu despacho ya no tiene por que perseguir facturas una y otra vez (ES)", ty:"Document/carousel", r:9, c:0, rp:1},
      {t:"La factura electronica obligatoria no va solo de dejar atras el papel (ES)", ty:"Document/carousel", r:12, c:0, rp:1},
      {t:"Many companies in Belgium think choosing a Peppol provider is a one-way decision", ty:"Document/carousel", r:7, c:0, rp:0},
      {t:"La JFE 2026 a confirme une chose essentielle sur la reforme de la facturation (FR)", ty:"Carousel", r:28, c:2, rp:4},
      {t:"Estem molt contents que MetaData hagi posat el focus en nosaltres (CA)", ty:"Article/Link", r:7, c:0, rp:1},
      {t:"Meet our Support team", ty:"Document/carousel", r:4, c:0, rp:1},
      {t:"We've launched B2Brouter's Startups Programme", ty:"Document/carousel", r:13, c:0, rp:3}
    ]},
    { name: "Dooap", posts: [
      {t:"Every AP Manager knows this feeling: you spot the fix, but IT has a three-week queue", ty:"Article/Link", r:11, c:0, rp:3},
      {t:"Last time we said 'something new is coming', we introduced Dooap Studio - agentic AP", ty:"Image", r:25, c:0, rp:3},
      {t:"Somewhere right now an AP manager is refreshing their inbox hoping an approval appeared", ty:"Image", r:17, c:0, rp:2},
      {t:"We are here - find the team and table next to registration", ty:"Video", r:24, c:2, rp:0},
      {t:"The Dynamics community is coming to Toronto - and so are we", ty:"Image", r:16, c:0, rp:1},
      {t:"Excited to introduce our latest Dooap Unleashed: Run With Us - Eftsure", ty:"Video", r:39, c:2, rp:1},
      {t:"This is what agentic AP automation looks like (Dooap Studio)", ty:"Video", r:17, c:0, rp:6},
      {t:"AP automation doesn't stop at the invoice - so why should your tech stack?", ty:"Video", r:71, c:10, rp:3},
      {t:"We saw a clear shift across DynamicsCon2026 and DynamicsMinds2026", ty:"Image", r:21, c:0, rp:0},
      {t:"Well, that's a wrap on DynamicsMinds", ty:"Carousel", r:70, c:4, rp:0},
      {t:"Great conversations", ty:"Video", r:9, c:1, rp:0},
      {t:"Set up and ready for 'Herd your AP with AI Agents'", ty:"Image", r:28, c:2, rp:3},
      {t:"The biggest problem in finance isn't the system", ty:"Video", r:21, c:3, rp:1},
      {t:"Sam Bush live here in Helsinki", ty:"Video", r:66, c:4, rp:0},
      {t:"What does AI literacy actually look like for a Dynamics 365 Finance team in 2026", ty:"Article/Link", r:10, c:0, rp:1},
      {t:"Love spending time with our partners all year around", ty:"Video", r:9, c:0, rp:2},
      {t:"With AP you have a lot of balls in the air - let Dooap help you herd them", ty:"Carousel", r:57, c:1, rp:2},
      {t:"Something new is coming", ty:"Image", r:20, c:1, rp:4},
      {t:"Join us at the Dynamic Communities Summit NA Roadshow in Vancouver", ty:"Carousel", r:16, c:0, rp:3},
      {t:"Approving invoices shouldn't keep you tied to your desk", ty:"Article/Link", r:10, c:1, rp:3},
      {t:"We are here in Tampa to talk about AI and AP for Dynamics 365 Finance", ty:"Image", r:49, c:3, rp:0},
      {t:"Our AP automation solution is designed for Microsoft D365FO", ty:"Document/carousel", r:4, c:0, rp:0},
      {t:"Great AP automation happens before you even know it", ty:"Video", r:16, c:0, rp:1},
      {t:"Thank you, Ellipse Solutions, for the highlight", ty:"Image", r:6, c:0, rp:0},
      {t:"Considering AP Automation for D365 Finance or BC", ty:"Article/Link", r:9, c:0, rp:2},
      {t:"Dooap the Dog and the team ready to show you AP automation", ty:"Image", r:10, c:0, rp:1},
      {t:"Next week - Wonderful, wonderful Copenhagen", ty:"Image", r:11, c:1, rp:2},
      {t:"Hear from one of our partners, Dana Chirieac from GraVoc", ty:"Video", r:8, c:0, rp:2},
      {t:"Continuing 'My one word for Dooap' - here's what Norman Maxwell said", ty:"Article/Link", r:15, c:0, rp:2},
      {t:"Since we started, we have not lost a single customer", ty:"Article/Link", r:11, c:1, rp:2}
    ]},
    { name: "Yavrio", posts: [
      {t:"A big couple of weeks for the Yavrio team - across North America and the UK", ty:"Carousel", r:69, c:1, rp:0},
      {t:"Cards on the Table (Yavrio Cards)", ty:"Carousel", r:44, c:7, rp:2},
      {t:"We're delighted to announce our partnership with Sabre Limited", ty:"Image", r:34, c:6, rp:0},
      {t:"260+ hours a year (finance time saved)", ty:"Image", r:15, c:0, rp:1},
      {t:"For finance teams still importing bank statements by CSV into Dynamics 365 BC", ty:"Document/carousel", r:14, c:0, rp:1},
      {t:"We are live now with Western Computer for our joint session on banking in Dynamics", ty:"Text", r:7, c:0, rp:0},
      {t:"Meet our North America Sales Director, Joshua Wilkinson", ty:"Image", r:59, c:6, rp:1},
      {t:"Still moving bank data into your finance system one CSV at a time?", ty:"Video", r:27, c:0, rp:1},
      {t:"The payment is accepted. But is the finance work actually done?", ty:"Image", r:48, c:1, rp:0},
      {t:"What a 2026 Yavrio is having so far", ty:"Carousel", r:110, c:9, rp:0},
      {t:"DynamicsMinds 2026 is done and what a week it's been", ty:"Carousel", r:108, c:5, rp:0},
      {t:"Finance teams BEFORE vs AFTER Yavrio", ty:"Video", r:48, c:5, rp:0},
      {t:"DynamicsMinds 2026", ty:"Image", r:61, c:5, rp:2},
      {t:"DynamicsCon 2026 wrapped and what a few days it was", ty:"Carousel", r:55, c:2, rp:0},
      {t:"Feet on the ground at Directions ASIA 2026 in Vietnam", ty:"Carousel", r:68, c:1, rp:1},
      {t:"Hello from a roasting Las Vegas - DynamicsCon2026", ty:"Image", r:99, c:10, rp:1},
      {t:"Sponsoring and attending Directions North America in Orlando", ty:"Image", r:62, c:4, rp:1},
      {t:"Yavrio is a WINNER of the Scaleup category at Innovate Finance", ty:"Image", r:160, c:22, rp:1},
      {t:"Every card payment sets off a chain of events most people never see", ty:"Image", r:25, c:3, rp:1},
      {t:"Directions North America is nearly here and the Yavrio team is ready for Orlando", ty:"Image", r:65, c:3, rp:3},
      {t:"Yavrio Out and About - This Week", ty:"Carousel", r:66, c:3, rp:0},
      {t:"Finance teams shouldn't be spending their time chasing transactions", ty:"Image", r:24, c:1, rp:0},
      {t:"Team Yavrio on the ground at the Microsoft AI Tour in Copenhagen", ty:"Image", r:53, c:2, rp:1},
      {t:"Yavrio Out & About: one of the biggest events in global tourism", ty:"Carousel", r:36, c:3, rp:0},
      {t:"Big news", ty:"Image", r:46, c:2, rp:6},
      {t:"The pace of technological change in financial services isn't slowing", ty:"Carousel", r:50, c:4, rp:0},
      {t:"Today we launched something special", ty:"Carousel", r:53, c:3, rp:3},
      {t:"Today we're launching Yavrio Cards: a cards payment solution embedded inside Microsoft Dynamics", ty:"Image", r:131, c:9, rp:5},
      {t:"More big news from Yavrio this week (leadership investment)", ty:"Image", r:75, c:20, rp:2},
      {t:"Proud to be sponsoring the Microsoft AI Tour in Copenhagen", ty:"Image", r:49, c:3, rp:3}
    ]},
    { name: "Rillion", posts: [
      {t:"AI transformation in finance is more about getting people onboard than the technology", ty:"Video", r:28, c:3, rp:4},
      {t:"If you'd told us our favourite team events would be the ones you track on Strava", ty:"Carousel", r:15, c:0, rp:0},
      {t:"48% of finance leaders say they want to be strategic advisors", ty:"Text", r:5, c:0, rp:0},
      {t:"Rillion + Stratas: taking AP automation in the UK to the next level", ty:"Video", r:22, c:2, rp:2},
      {t:"Spotted on top of the Empire State Building - Rillion", ty:"Image", r:35, c:0, rp:1},
      {t:"If you're not optimizing your vacation as much as your AP processes", ty:"Document/carousel", r:10, c:0, rp:0},
      {t:"Peter Egehoved (CFO Dreamdata) on where AI fits in finance", ty:"Text", r:57, c:8, rp:0},
      {t:"If you recognise yourself in any of these, you're not alone", ty:"Document/carousel", r:7, c:0, rp:0},
      {t:"Big news (Rillion + Pinewood.AI)", ty:"Image", r:49, c:1, rp:11},
      {t:"Monika Pers (CFO) on where AI belongs in finance", ty:"Text", r:12, c:1, rp:0},
      {t:"Just got back from two of the most energizing days I've had in a long time", ty:"Image", r:52, c:8, rp:1},
      {t:"26% of CFOs say lack of AI competence is the single biggest barrier to adoption", ty:"Text", r:18, c:1, rp:1},
      {t:"40% of CFOs see fraud and anomaly detection as the biggest AI opportunity in finance", ty:"Image", r:17, c:1, rp:1},
      {t:"Our marketing team swapped their laptops for race bibs - Blodomloppet", ty:"Carousel", r:35, c:3, rp:1},
      {t:"Last week we released The Nordic Finance AI Report 2026", ty:"Image", r:13, c:0, rp:1},
      {t:"Rillion AI Day", ty:"Image", r:53, c:14, rp:1},
      {t:"Most companies invest in automating existing processes, not in questioning them", ty:"Document/carousel", r:25, c:1, rp:1},
      {t:"250 CFOs across Sweden, Denmark and Finland told us where AI in finance actually stands", ty:"Document/carousel", r:18, c:7, rp:3},
      {t:"Lots of travel these past few weeks, but it's experiences like these that make the job", ty:"Carousel", r:57, c:3, rp:2},
      {t:"Still reflecting on the conversations at Sage Future in San Francisco", ty:"Image", r:63, c:4, rp:1},
      {t:"Puppies and candy", ty:"Carousel", r:65, c:5, rp:1},
      {t:"Kicking off an exciting few days at DynamicsCon", ty:"Carousel", r:52, c:8, rp:2},
      {t:"Week two of three back-to-back industry events - ERP Summit", ty:"Image", r:45, c:0, rp:1},
      {t:"When new to SaaS, you learn from the SaaSiest", ty:"Image", r:92, c:4, rp:1},
      {t:"We are officially live at Sage Future - swing by the Rillion booth", ty:"Image", r:62, c:4, rp:2},
      {t:"Sage Intacct users, this one's for you", ty:"Document/carousel", r:23, c:2, rp:5},
      {t:"Our CEO Daniel de Sousa joined a conversation at the Swedish Parliament", ty:"Video", r:45, c:1, rp:1},
      {t:"Will we see you at CFOradar 2026 next week", ty:"Image", r:24, c:0, rp:1},
      {t:"There's A LOT of talk about AI in finance right now", ty:"Video", r:14, c:2, rp:0},
      {t:"Are you vibe coding tools for your finance team", ty:"Image", r:16, c:1, rp:4}
    ]},
    { name: "Fidesic", posts: [
      {t:"How to set up your purchase order matching", ty:"Article/Link", r:0, c:0, rp:0},
      {t:"AI and human ingenuity are powering a bold new operating model", ty:"Image", r:0, c:0, rp:0},
      {t:"Modern AI-based invoice capture uses ML models trained on millions of invoices", ty:"Article/Link", r:0, c:0, rp:0},
      {t:"Unsurprisingly, not all AI projects are a success", ty:"Carousel", r:1, c:0, rp:0},
      {t:"Fidesic is the strongest AP automation choice for organizations running Microsoft Dynamics", ty:"Article/Link", r:0, c:0, rp:0},
      {t:"95% of enterprise generative AI pilots fail to deliver measurable results", ty:"Video", r:9, c:1, rp:2},
      {t:"Financial close is evolving from a manual task to an automated, continuous process", ty:"Image", r:1, c:0, rp:0},
      {t:"95% of enterprise generative AI pilots fail to deliver any measurable P&L impact", ty:"Article/Link", r:2, c:0, rp:0},
      {t:"Something hiding in plain sight in Dynamics GP that could make a difference", ty:"Article/Link", r:0, c:0, rp:0},
      {t:"Did you know... (Fidesic fun fact)", ty:"Image", r:1, c:0, rp:1},
      {t:"Fidesic has officially joined Knights of GP", ty:"Image", r:17, c:2, rp:3},
      {t:"Why Accruals and Deferrals Matter for Financial Accuracy", ty:"Image", r:1, c:0, rp:0},
      {t:"Budget pressure? It's AP's time to shine", ty:"Article/Link", r:0, c:0, rp:0},
      {t:"If your team uses Microsoft Dynamics GP or BC to manage multiple locations", ty:"Image", r:4, c:0, rp:0},
      {t:"Did you know...", ty:"Image", r:7, c:1, rp:1},
      {t:"With only ... (post truncated in export)", ty:"Article/Link", r:1, c:0, rp:0},
      {t:"Turning AP into a strategic function doesn't require a massive transformation", ty:"Article/Link", r:1, c:0, rp:0},
      {t:"Microsoft Dynamics 365 Business Central is built for a wide range of business sizes", ty:"Article/Link", r:0, c:0, rp:0},
      {t:"Who to see at DirectionsNA", ty:"Image", r:55, c:3, rp:1},
      {t:"Attending Directions NA", ty:"Carousel", r:2, c:0, rp:0},
      {t:"Directions NA 2026 is in full swing in Orlando with Day 1 keynote", ty:"Image", r:6, c:1, rp:1},
      {t:"Huge thanks to ERP Software Blog for including us on their Best ERP Tools list", ty:"Image", r:7, c:2, rp:2},
      {t:"Stop by the booth and say Hi", ty:"Image", r:18, c:0, rp:2},
      {t:"The teams from PayTrace and Fidesic AP will be at Directions North America in Orlando", ty:"Carousel", r:18, c:2, rp:5},
      {t:"When an AP tool is built natively inside Business Central, implementation looks different", ty:"Image", r:0, c:0, rp:0},
      {t:"Almost two weeks away from DirectionsNA", ty:"Image", r:21, c:3, rp:1},
      {t:"Have you seen Fidesic Free", ty:"Image", r:1, c:0, rp:0},
      {t:"Wire transfers are a reliable way to send and receive money, but they have limitations", ty:"Image", r:2, c:1, rp:0},
      {t:"Deploying a new invoice management system across your entire vendor network at once", ty:"Article/Link", r:2, c:0, rp:0},
      {t:"The AP Turnover Ratio gives you frequency", ty:"Article/Link", r:0, c:0, rp:0}
    ]},
    { name: "Tipalti", posts: [
      {t:"Mechanical, performance, sync, master recording", ty:"Image", r:0, c:0, rp:0},
      {t:"Before Tipalti, Thematic's finance team manually managed international payments", ty:"Video", r:4, c:0, rp:1},
      {t:"When did your team last screen a supplier for sanctions exposure?", ty:"Image", r:4, c:0, rp:0},
      {t:"Brought the Israeli Design Leadership community together at the Tipalti office", ty:"Carousel", r:135, c:14, rp:3},
      {t:"The Tipalti team will be in Berlin for the World Finance Forum", ty:"Image", r:12, c:1, rp:2},
      {t:"Is your marketplace's payment infrastructure built to scale or just to function?", ty:"Article/Link", r:2, c:0, rp:0},
      {t:"A hypothetical about manual processes", ty:"Text", r:4, c:1, rp:0},
      {t:"Ask any finance team that's made the switch to automation what they regret", ty:"Text", r:1, c:0, rp:0},
      {t:"Thematic: creators get free licensed music, artists get meaningful payouts", ty:"Image", r:8, c:0, rp:1},
      {t:"Prodege expanded globally and maintained compliance throughout", ty:"Video", r:7, c:0, rp:1},
      {t:"Trade fragmentation, high interest rates, tighter capital, and geopolitical uncertainty", ty:"Image", r:6, c:0, rp:0},
      {t:"A 30-day close used to be normal", ty:"Image", r:12, c:3, rp:2},
      {t:"Finance leaders are operating in a different environment than a few years ago", ty:"Image", r:10, c:0, rp:1},
      {t:"DreamHost's finance team wanted full visibility of every transaction", ty:"Video", r:5, c:0, rp:0},
      {t:"The next chapter of digital commerce is being executed by AI acting for consumers", ty:"Image", r:4, c:0, rp:1},
      {t:"Cubic Games was managing over 180 vendors across global markets", ty:"Image", r:8, c:0, rp:0},
      {t:"Manual payment processes don't scale", ty:"Text", r:10, c:0, rp:0},
      {t:"A few days out from World Finance Forum in Amsterdam and the Tipalti team is ready", ty:"Image", r:7, c:0, rp:0},
      {t:"Splice's finance team would spend two weeks every quarter on manual work", ty:"Image", r:9, c:0, rp:0},
      {t:"We're heading your way, Vancouver", ty:"Video", r:10, c:0, rp:1},
      {t:"Proud to sponsor the Spring 2026 CFO Leadership Conference in Boston", ty:"Carousel", r:81, c:6, rp:3},
      {t:"Three-way matching by hand is tedious, error-prone, and slow", ty:"Image", r:21, c:0, rp:1},
      {t:"The questions finance leaders are asking about AI has changed", ty:"Video", r:127, c:4, rp:6},
      {t:"Approval bottlenecks don't just slow down payments", ty:"Image", r:17, c:2, rp:2},
      {t:"For a gaming studio managing over 180 active vendors, AP was a challenge", ty:"Image", r:9, c:0, rp:0},
      {t:"Tariffs and trade fragmentation are reshaping the global economy", ty:"Image", r:6, c:0, rp:0},
      {t:"The bar for enterprise software has been quietly reset", ty:"Image", r:3, c:0, rp:0},
      {t:"Show me all unpaid invoices over $10K", ty:"Image", r:13, c:0, rp:0},
      {t:"Five years ago, Lantern Community Services ran on paper", ty:"Image", r:5, c:0, rp:0},
      {t:"Technology investments are growing faster and more complex than ever", ty:"Image", r:5, c:0, rp:0}
    ]},
    { name: "Stampli", posts: [
      {t:"I spent ten years as an accountant before I ever touched marketing", ty:"Video", r:49, c:3, rp:4},
      {t:"What changes when finance teams can analyze data that used to be slow and manual", ty:"Article/Link", r:13, c:0, rp:1},
      {t:"Finance teams don't run out of good questions", ty:"Document/carousel", r:31, c:0, rp:12},
      {t:"Accounts Payable is where Procure-to-Pay either works or breaks", ty:"Article/Link", r:16, c:0, rp:6},
      {t:"Vendor renewal coming up? A lot can change since the last contract", ty:"Article/Link", r:11, c:1, rp:4},
      {t:"Strong customer feedback on real value - one connected P2P story", ty:"Article/Link", r:37, c:1, rp:16},
      {t:"Finance teams don't run out of useful questions", ty:"Article/Link", r:22, c:1, rp:6},
      {t:"ACH risks don't start at the bank portal - they often start earlier", ty:"Article/Link", r:17, c:3, rp:7},
      {t:"Meaningful savings can hide in everyday finance data", ty:"Image", r:30, c:3, rp:10},
      {t:"Built to scale your business, not your headcount", ty:"Article/Link", r:25, c:0, rp:11},
      {t:"Vendor concentration risk is hiding in your AP data", ty:"Article/Link", r:11, c:0, rp:1},
      {t:"Day 2 at SageFuture and the energy is still going strong", ty:"Image", r:42, c:1, rp:1},
      {t:"Day 1 of SageFuture in the books", ty:"Carousel", r:91, c:1, rp:5},
      {t:"We're about to see the death of the dashboard", ty:"Image", r:82, c:8, rp:23},
      {t:"Budget variance usually doesn't start with one big decision", ty:"Article/Link", r:7, c:0, rp:2},
      {t:"Cash flow opportunities often hide in Accounts Payable", ty:"Article/Link", r:18, c:2, rp:4},
      {t:"The data moving through finance systems holds a story teams never see", ty:"Article/Link", r:25, c:1, rp:6},
      {t:"The most valuable signals in finance are buried where traditional BI can't reach", ty:"Video", r:52, c:2, rp:6},
      {t:"We're launching something big: an agentic financial analyst you can ask anything", ty:"Video", r:145, c:3, rp:21},
      {t:"Ask your agentic financial analyst anything", ty:"Video", r:39, c:0, rp:22},
      {t:"A great time at the Nashville career fair", ty:"Carousel", r:43, c:1, rp:5},
      {t:"Stampli Deep Finance transforms raw finance data into executive spend intelligence", ty:"Article/Link", r:46, c:2, rp:29},
      {t:"America's Group automated workflows instead of hiring more AP staff with every acquisition", ty:"Article/Link", r:14, c:0, rp:6},
      {t:"No matter your ERP, Stampli fits right in", ty:"Article/Link", r:17, c:0, rp:9},
      {t:"Corporate cards don't have to mean losing control of spend", ty:"Article/Link", r:17, c:0, rp:5},
      {t:"Finance professionals paired with the right platform turn complexity into advantage", ty:"Image", r:11, c:0, rp:3},
      {t:"We're grateful for all our customers", ty:"Article/Link", r:65, c:0, rp:35},
      {t:"Those little clicks add up", ty:"Video", r:25, c:0, rp:10}
    ]}
  ]
};
