/* =========================================================================
   LinkedIn post-engagement data for the Continia competitor dashboard.
   Public engagement on each company's recent posts (reactions / comments /
   reposts). Totals + averages are computed in dashboard.js from these raw
   posts, so the comparison table can never drift from the source.

   Source: Assets/linkedin_post_engagement_report_Sep 9_2026.txt (captured 2026-09-09).
   "t" is the post title (opening line of the post, normalized to plain ASCII;
   a trailing "..." means LinkedIn's own copy continued), "ty" is the content
   type pill. The report lists newest-first per company; we keep the 50
   most-recent posts each (fewer where the page had fewer: Equisys 39,
   AMC Banking 22, Qvalia 15).

   On the tracking list but deliberately excluded (watch, not card - see
   FULL-UPDATE.md): incedo-inc (consulting firm), signup-software (Truvio's
   former brand, already the ExFlow/Truvio card), stripe (payments benchmark).
   ========================================================================= */

window.LI_DATA = {
  source: "LinkedIn public engagement",
  captured: "2026-09-09",
  windowLabel: "up to 50 recent posts each · public engagement",
  companies: [
    { name: "Continia Software", ours: true, posts: [
      {t:"Thank you, Days of Knowledge ANZ It's a wrap on two...", ty:"Image", r:83, c:0, rp:0},
      {t:"Protecting the world's water shouldn't mean...", ty:"Image", r:17, c:0, rp:2},
      {t:"It's about time... we found out who's faster...", ty:"Image", r:98, c:0, rp:0},
      {t:"It's about time you stopped doing these 5...", ty:"Document/carousel", r:36, c:2, rp:1},
      {t:"12 free features your Business Central setup...", ty:"Document/carousel", r:41, c:0, rp:5},
      {t:"We've got room left on the team! If the summer break...", ty:"Document/carousel", r:34, c:0, rp:4},
      {t:"We're back from a great DynamicsCon in Ghana...", ty:"Image", r:63, c:2, rp:2},
      {t:"More than 1,000 active Continia solutions Our...", ty:"Image", r:119, c:1, rp:8},
      {t:"Submitting expenses just got even easier! These...", ty:"Document/carousel", r:37, c:5, rp:8},
      {t:"It's about time... for an ice-cream break! It's...", ty:"Image", r:70, c:1, rp:0},
      {t:"Our biggest team meetup yet Last week, we brought our...", ty:"Image", r:243, c:4, rp:6},
      {t:"The Elevate tour continues - this time in...", ty:"Image", r:71, c:1, rp:0},
      {t:"It's about time... we cycled to work In May, the...", ty:"Image", r:69, c:1, rp:0},
      {t:"250 Continia-losninger er en god grund til...", ty:"Image", r:70, c:1, rp:2},
      {t:"Thanks for a great time at DynamicsMinds! It's...", ty:"Image", r:93, c:2, rp:0},
      {t:"Continia is growing - swipe to find your next...", ty:"Document/carousel", r:42, c:0, rp:0},
      {t:"That's a wrap on Directions ASIA A big thank you to...", ty:"Image", r:59, c:0, rp:0},
      {t:"Is your Accounts Receivable setup as...", ty:"Document/carousel", r:39, c:0, rp:0},
      {t:"Celebrating our very own Microsoft MVP Last week...", ty:"Image", r:217, c:17, rp:1},
      {t:"25 ars samarbejde og +500 aktive...", ty:"Image", r:75, c:2, rp:2},
      {t:"Celebrating the first release of 2026 2026 R1 is...", ty:"Image", r:80, c:0, rp:1},
      {t:"Your e-invoicing data is only as safe as your...", ty:"Image", r:28, c:0, rp:3},
      {t:"Hopping into Easter... This week, a little Easter surprise made...", ty:"Image", r:61, c:0, rp:2},
      {t:"Happy birthday to our CEO! Last week, we celebrated a...", ty:"Image", r:208, c:20, rp:0},
      {t:"Get a first look at 2026 R1! Continia's first release of the...", ty:"Document/carousel", r:31, c:0, rp:3},
      {t:"Your BC setup is almost there. Why not upgrade...", ty:"Video", r:34, c:0, rp:4},
      {t:"Vi fejrer +500 implementerede...", ty:"Image", r:77, c:0, rp:3},
      {t:"Where to meet Continia this spring and...", ty:"Document/carousel", r:34, c:0, rp:3},
      {t:"Lap times (almost) as quick as our invoice...", ty:"Image", r:53, c:0, rp:1},
      {t:"Every AP automation pitch this year sounds...", ty:"Image", r:21, c:0, rp:2},
      {t:"Same Monday, two very different workdays It's...", ty:"Image", r:30, c:0, rp:1},
      {t:"Tak for to laererige dage pa Hindsgavl Slot Aret er kommet godt fra start for...", ty:"Image", r:107, c:3, rp:4},
      {t:"How far is your business in adopting...", ty:"Poll", r:10, c:2, rp:2},
      {t:"2026 R1: A big step forward for AR automation...", ty:"Video", r:84, c:2, rp:6},
      {t:"Getting ready for ViDA? Don't leave it until the last-minute...", ty:"Document/carousel", r:14, c:2, rp:0},
      {t:"The office is quiet. Why not spend the summer...", ty:"Image", r:23, c:0, rp:0},
      {t:"It's a wrap: Our biggest Company Day yet! Last...", ty:"Image", r:121, c:4, rp:3},
      {t:"If you could remove one repetitive task from...", ty:"Document/carousel", r:32, c:5, rp:5},
      {t:"Separate accounts-but it's one relationship...", ty:"Image", r:33, c:1, rp:5},
      {t:"Du er inviteret: Kom med til danske webinarer...", ty:"Document/carousel", r:24, c:0, rp:1},
      {t:"Where does your time go? Finance teams spend countless hours...", ty:"Poll", r:12, c:0, rp:1},
      {t:"Thank you for a fantastic Directions EMEA!...", ty:"Image", r:212, c:8, rp:6},
      {t:"Continia Elevate comes to France! Today, we have the...", ty:"Image", r:82, c:1, rp:5},
      {t:"Prost to the second release of 2025! Last week,...", ty:"Image", r:137, c:0, rp:6},
      {t:"Celebrating steady growth We're proud to share that...", ty:"Image", r:173, c:2, rp:4},
      {t:"We're investing in future talent There's no doubt that...", ty:"Image", r:97, c:1, rp:4},
      {t:"We're at the E-Invoicing Summit in Vienna! At...", ty:"Image", r:47, c:0, rp:3},
      {t:"Happy Holidays from all of us at Continia! As...", ty:"Video", r:64, c:0, rp:0},
      {t:"See Continia in action, at your own pace Curious...", ty:"Image", r:36, c:1, rp:4},
      {t:"On the road for work? Mileage reporting...", ty:"Video", r:21, c:0, rp:1}
    ]},
    { name: "Truvio", posts: [
      {t:"Today, developers from across our partner community have taken over Aarhus for the...", ty:"Image", r:21, c:0, rp:0},
      {t:"En hel dag vaek fra indbakken skal vaere tiden vaerd. Derfor har vi sammen med...", ty:"Image", r:16, c:0, rp:2},
      {t:"For St Vincent de Paul Society NSW, modernising Accounts Payable meant more than...", ty:"Image", r:22, c:1, rp:5},
      {t:"Day 1 at Days of Knowledge - ANZ is well underway! We've just wrapped up our...", ty:"Image", r:22, c:0, rp:5},
      {t:"Your AP dashboard might say \"automated.\" Your AP team might tell a different story...", ty:"Image", r:13, c:0, rp:2},
      {t:"Remember when waiting was just part of the process? Waiting on approvals. Tracking...", ty:"Image", r:16, c:0, rp:2},
      {t:"How do you manage more than 200,000 products across your own webshop and a growing...", ty:"Image", r:13, c:0, rp:1},
      {t:"November 14, 2026. From that date, SWIFT CBPR+ will no longer accept cross-border...", ty:"Image", r:11, c:0, rp:1},
      {t:"Great start to Days of Knowledge ANZ! Today, David Williams, GAICD. and I had the...", ty:"Image", r:66, c:4, rp:2},
      {t:"B2B-kunder begynder ikke nodvendigvis deres kobsrejse pa jeres webshop. De soger...", ty:"Image", r:10, c:2, rp:0},
      {t:"Invoice capture is only one part of accounts payable automation. What happens when...", ty:"Image", r:35, c:2, rp:6},
      {t:"Running, walking and cheering each other on. This week, colleagues from our...", ty:"Image", r:78, c:0, rp:1},
      {t:"4 minutes versus 17 minutes per invoice. That was the difference measured between...", ty:"Video", r:16, c:0, rp:3},
      {t:"One last conversation before we officially close out summer. We're wrapping up...", ty:"Image", r:15, c:0, rp:3},
      {t:"AI er allerede ved at aendre den made, B2B-kunder finder, sammenligner og vaelger...", ty:"Image", r:15, c:0, rp:1},
      {t:"The Commerce Product Brief is already next week. Our Product Managers are putting...", ty:"Image", r:17, c:0, rp:5},
      {t:"Nine steps. Zero manual touchpoints. That's what an automated payment lifecycle in...", ty:"Image", r:16, c:0, rp:3},
      {t:"A little sneak peek at what's coming next to Truvio Talks... We're not done with...", ty:"Image", r:19, c:0, rp:4},
      {t:"When you're in the middle of a complex ERP transformation, a smooth implementation...", ty:"Image", r:18, c:0, rp:0},
      {t:"Vi glaeder os til at vaere med, nar Computerworld Events saetter fokus pa vejen videre...", ty:"Image", r:22, c:0, rp:1},
      {t:"Hylke Britstra is taking the stage at Directions for Enterprise 2026 in Copenhagen...", ty:"Image", r:27, c:0, rp:2},
      {t:"Summer isn't over yet, and neither is your chance to win! The Truvio Talks Summer...", ty:"Image", r:16, c:0, rp:5},
      {t:"Ready to shorten your order-to-cash cycle? Join us on August 13th to see how the...", ty:"Event", r:11, c:0, rp:4},
      {t:"We're excited to share that Truvio is a Gold Sponsor at Days of Knowledge - ANZ...", ty:"Image", r:19, c:0, rp:3},
      {t:"Manual payments cost more than money. Every file upload, spreadsheet update, and...", ty:"Image", r:26, c:0, rp:5},
      {t:"Finance teams shouldn't have to spend their day chasing information. When...", ty:"Event", r:20, c:0, rp:9},
      {t:"Ready for a vacation... but worried your finance operations might not be? If your...", ty:"Event", r:22, c:0, rp:6},
      {t:"Less than one month to go until Truvio Commerce Partner Days 2026! On September...", ty:"Image", r:27, c:0, rp:2},
      {t:"Tomorrow, new EU packaging rules begin to apply. From 12th of August, 2026, the...", ty:"Image", r:16, c:0, rp:7},
      {t:"I am looking forward to this non-product-oriented, business-focused discussion with...", ty:"Image", r:8, c:0, rp:2},
      {t:"Last week, we attended Forretning Online in Aarhus, Denmark - a full-day conference...", ty:"Image", r:34, c:2, rp:3},
      {t:"When customers need a spare part, finding the right one should be simple - even when...", ty:"Video", r:27, c:0, rp:8},
      {t:"Fraud risk is hiding in everyday finance workflows - emailed invoices, manual entry,...", ty:"Event", r:13, c:0, rp:2},
      {t:"Only 2 more days until the next episode of Truvio Talks! Vacation season has a...", ty:"Event", r:3, c:0, rp:0},
      {t:"This clip is just a glimpse into tomorrow's conversation. Join Chris Robbins...", ty:"Video", r:10, c:0, rp:0},
      {t:"The numbers don't lie - B2B eCommerce is reshaping how manufacturers, distributors,...", ty:"Event", r:16, c:0, rp:6},
      {t:"Work Like You're on Vacation... and you might just win the ultimate summer prize...", ty:"Video", r:38, c:0, rp:6},
      {t:"A full day of B2B eCommerce, product data, PIM, AI, and digital sales in Aarhus,...", ty:"Image", r:71, c:3, rp:1},
      {t:"Holiday reading doesn't have to be fiction. If you're looking for something...", ty:"Video", r:13, c:0, rp:1},
      {t:"DynamicsMinds 2026. Between arcade game battles in our booth, packed sessions,...", ty:"Image", r:74, c:4, rp:6},
      {t:"A great start to Truvio Commerce Customer Day in Aarhus! Today, we're gathered at...", ty:"Image", r:88, c:3, rp:3},
      {t:"Sidste chance for at tilmelde dig Truvio Commerce Customer Day 2026! I morgen samles...", ty:"Image", r:38, c:2, rp:4},
      {t:"How dependent is your business on the people who keep your ERP running? If that...", ty:"Video", r:13, c:0, rp:3},
      {t:"Greetings from a very sunny Portoroz! We're at DynamicsMinds kicking off day 2...", ty:"Image", r:105, c:3, rp:1},
      {t:"Finance teams don't need more AI for the sake of AI. They need better ways to...", ty:"Video", r:23, c:0, rp:4},
      {t:"Early bird pricing for Truvio Commerce Partner Days 2026 ends tomorrow, July 15...", ty:"Video", r:19, c:0, rp:3},
      {t:"This week, we're hosting two APJ Partner Training sessions for D365 F&O partners...", ty:"Image", r:14, c:0, rp:3},
      {t:"How does a manufacturer with 40,000+ spare parts give 60 global dealers 24/7...", ty:"Event", r:15, c:1, rp:10},
      {t:"We're live at DYNAfair in Dortmund, Germany! The Truvio team is on the floor and...", ty:"Image", r:62, c:4, rp:3},
      {t:"ERP success is rarely driven by a single vendor. The most successful Microsoft...", ty:"Event", r:21, c:3, rp:3}
    ]},
    { name: "Equisys", posts: [
      {t:"Whether you're just starting to consider a change to your processes or actively...", ty:"Image", r:1, c:0, rp:3},
      {t:"Join us as our panel of product experts and support specialists answer your Zetadocs...", ty:"Image", r:2, c:0, rp:3},
      {t:"Our Implementation Services help Business Central partners deliver faster, smoother...", ty:"Image", r:4, c:0, rp:3},
      {t:"Missed our recent webinar? Catch up now! Discover the best AP automation solution...", ty:"Video", r:5, c:0, rp:2},
      {t:"Manage your documents more effectively, rather than just storing them in a...", ty:"Image", r:3, c:0, rp:4},
      {t:"This month we're celebrating 15 years of the Equisys blog! Here's some of the...", ty:"Document/carousel", r:3, c:0, rp:1},
      {t:"Looking forward to being part of this great event!", ty:"Image", r:1, c:0, rp:0},
      {t:"Cut costs without compromising control. Discover how AP automation reduces invoice...", ty:"Image", r:4, c:0, rp:2},
      {t:"With Zetadocs, you can drag and drop supporting documents against a journal entry in...", ty:"Image", r:4, c:1, rp:2},
      {t:"We're just a few hours away from our webinar, 'Discover THE BEST AP Automation...", ty:"Image", r:0, c:0, rp:1},
      {t:"The future of accounts payable is automated. Explore expert perspectives on how AI...", ty:"Article/Link", r:2, c:0, rp:0},
      {t:"There's less than 24 hours left to register for our webinar - 'Discover THE BEST AP...", ty:"Image", r:2, c:0, rp:3},
      {t:"Still chasing approvals and fixing errors? AP automation removes bottlenecks, speeds...", ty:"Article/Link", r:0, c:0, rp:0},
      {t:"AI in ERP is accelerating fast, and ISVs are leading the way with practical,...", ty:"Article/Link", r:3, c:0, rp:2},
      {t:"Accounting teams in the manufacturing industry (and beyond) are facing challenges...", ty:"Article/Link", r:1, c:0, rp:0},
      {t:"Join us for our webinar! On Tuesday 30 September, we will host a webinar: \"Seamless...", ty:"Article/Link", r:0, c:0, rp:1},
      {t:"Looking for a smarter way to manage employee expenses and ensure compliant claims?...", ty:"Image", r:3, c:0, rp:3},
      {t:"We had an amazing first day at Directions North America and can't wait to see what...", ty:"Image", r:15, c:0, rp:5},
      {t:"We'll be in Orlando, Florida next week for Directions North America, and we'd love...", ty:"Image", r:5, c:0, rp:3},
      {t:"We're headed to Directions in Orlando, Florida in 2 weeks. We'll be at Booth E-32...", ty:"Image", r:6, c:0, rp:4},
      {t:"Deliver smarter, not harder! Customize how your documents reach the right people,...", ty:"Image", r:2, c:0, rp:0},
      {t:"Zetadocs Expenses offers a smooth expense workflow right out-of-the-box, with...", ty:"Image", r:4, c:0, rp:1},
      {t:"It's not too late to reserve your space on today's Lunch & Learn event! This event...", ty:"Image", r:3, c:0, rp:5},
      {t:"It's not too late - join a Lunch & Learn event this week to learn how to get even...", ty:"Image", r:3, c:0, rp:2},
      {t:"Our Lunch & Learn series starts next week! Are you registered yet? Each session will...", ty:"Image", r:0, c:0, rp:1},
      {t:"Looking for an expense management solution built for Business Central, ready to go...", ty:"Image", r:7, c:0, rp:2},
      {t:"Even the most well-written expense policies can prove difficult to enforce across a...", ty:"Image", r:7, c:0, rp:4},
      {t:"See how Zetadocs can transform the way you work. Book a demo today to explore any of...", ty:"Image", r:6, c:0, rp:4},
      {t:"Zetadocs Delivery helps finance teams spend less time on admin and more time on what...", ty:"Image", r:3, c:0, rp:2},
      {t:"Learn how to build a clear travel and entertainment expenses policy that's easy to...", ty:"Image", r:1, c:0, rp:1},
      {t:"Many employees feel unsure about what they can expense, even if upper management...", ty:"Image", r:1, c:0, rp:1},
      {t:"Thank you to all who stopped by our booth at Directions #EMEA2025! Our team have had...", ty:"Image", r:11, c:0, rp:2},
      {t:"Our team is really enjoying the informative sessions and great conversations...", ty:"Image", r:1, c:0, rp:0},
      {t:"We're delighted to be at Directions #EMEA2025 in Poznan! Be sure to come and visit...", ty:"Image", r:23, c:0, rp:5},
      {t:"We're excited to be heading to Directions EMEA next week! If you're attending, we'd...", ty:"Image", r:14, c:0, rp:7},
      {t:"It's almost time for Demo Week! From October 20-24, we're offering live,...", ty:"Image", r:3, c:0, rp:2},
      {t:"We're excited to take part in the Expense Reporting Comparison Showcase for Business...", ty:"Image", r:5, c:0, rp:1},
      {t:"Our customers love how easy it is to attach documents to the right Business Central...", ty:"Image", r:7, c:0, rp:1},
      {t:"Zetadocs Expenses provides a powerful solution that's simple to manage. Learn more...", ty:"Image", r:3, c:0, rp:2}
    ]},
    { name: "Medius", posts: [
      {t:"\"Within the first days of France's e-invoicing mandate, thousands of invoices have...", ty:"Image", r:37, c:0, rp:8},
      {t:"Are you a leader in finance, tax, tech, or compliance? We've got the perfect event...", ty:"Image", r:20, c:0, rp:1},
      {t:"87% of finance leaders have personally ignored a small expense, reimbursement, or...", ty:"Document/carousel", r:7, c:0, rp:0},
      {t:"We're thrilled to announce that Medius has earned three prestigious G2 badges in the...", ty:"Image", r:36, c:1, rp:9},
      {t:"Finance leaders know fraud when they see it. But what happens when the line gets...", ty:"Poll", r:2, c:0, rp:0},
      {t:"September is a good month to sort out AP. We have a full webinar lineup covering...", ty:"Document/carousel", r:14, c:0, rp:3},
      {t:"Not sure which AP automation features actually matter, and which are just on the...", ty:"Image", r:8, c:0, rp:2},
      {t:"Medius' Financial Census 2026 is officially here. Across 2,386 senior finance...", ty:"Document/carousel", r:38, c:0, rp:15},
      {t:"What better way to close out the week than with a new edition of MediusExplains?...", ty:"Document/carousel", r:12, c:0, rp:3},
      {t:"Join the Medius team at the upcoming inPOWER User Conference, taking place September...", ty:"Image", r:12, c:1, rp:0},
      {t:"Mark your calendars! Our Top Tips in Action live interactive webinar is coming up on...", ty:"Image", r:12, c:0, rp:4},
      {t:"Invoices processed in one day. 99%+ touchless capture. Approval routing that learns...", ty:"Image", r:26, c:0, rp:9},
      {t:"We had a great time this week at the Microsoft AI Business Solutions Partner...", ty:"Image", r:63, c:0, rp:1},
      {t:"58% of AP teams are already using or piloting AI. The other 42% are watching the gap...", ty:"Image", r:12, c:0, rp:1},
      {t:"Join us on August 26 for our Explore Medius: Compliance & E-invoicing live webinar...", ty:"Image", r:67, c:0, rp:5},
      {t:"What are the most common causes of late payments in B2B? Invoice errors, approval...", ty:"Article/Link", r:6, c:0, rp:0},
      {t:"A failed invoice match in manufacturing isn't just an AP problem. It delays supplier...", ty:"Article/Link", r:7, c:0, rp:2},
      {t:"Finance and diplomacy have more in common than you'd think. Both run on trust,...", ty:"Image", r:137, c:1, rp:7},
      {t:"Duplicate payments in retail don't usually look like duplicates. Same invoice,...", ty:"Article/Link", r:7, c:0, rp:0},
      {t:"If July gives you a little breathing room, why not use it to learn something new...", ty:"Document/carousel", r:10, c:0, rp:1},
      {t:"A new edition of MediusExplains? Don't mind if we do! Today, we're discussing how AP...", ty:"Document/carousel", r:12, c:0, rp:1},
      {t:"Rapid growth in logistics often masks a dangerous reality: operational complexity is...", ty:"Document/carousel", r:7, c:1, rp:1},
      {t:"Speed used to be the whole AP conversation. Process faster, close faster, repeat...", ty:"Image", r:65, c:0, rp:3},
      {t:"We're excited to return with a new edition of our MediusAsks series. This series...", ty:"Video", r:20, c:0, rp:1},
      {t:"Got 30 minutes? We've got plenty of reasons to spend them with us in June. We have...", ty:"Document/carousel", r:12, c:0, rp:0},
      {t:"Three days. A very nice corner of Slovenia. And more AP conversations than we can...", ty:"Image", r:69, c:7, rp:0},
      {t:"We had an amazing day 1 at the Gartner Finance Symposium/Xpo 2026! We greeted...", ty:"Image", r:108, c:0, rp:5},
      {t:"Day one at DynamicsMinds and the Medius team has landed in Portoroz. We're here...", ty:"Image", r:53, c:4, rp:0},
      {t:"It was great spending time at SSOW Europe this week with customers, partners, and...", ty:"Image", r:52, c:2, rp:0},
      {t:"Day one at Shared Services and Outsourcing Week Europe is in the books. The...", ty:"Image", r:55, c:1, rp:3},
      {t:"Q1 core value award winners announced! Every quarter, we recognize the people at...", ty:"Document/carousel", r:38, c:4, rp:1},
      {t:"Looking forward to this. Hope to see you join us on July 15.", ty:"Image", r:25, c:0, rp:5},
      {t:"The global shift to e-invoicing: are you ready? E-invoicing has revolutionized...", ty:"Document/carousel", r:13, c:1, rp:4},
      {t:"In construction, slow AP processes are a bottleneck. They're also a project risk...", ty:"Document/carousel", r:12, c:0, rp:4},
      {t:"It's a new month - and that means a new edition of MediusExplains! Today, we're...", ty:"Document/carousel", r:6, c:0, rp:1},
      {t:"What's the ROI of accounts payable automation? It depends on where you're starting...", ty:"Document/carousel", r:15, c:0, rp:5},
      {t:"Rapid growth in logistics often masks a dangerous reality: operational complexity is...", ty:"Document/carousel", r:16, c:1, rp:2},
      {t:"Join us on August 20 for our Medius Momentum: Q3 2026 Product Update, a live webinar...", ty:"Image", r:35, c:2, rp:4},
      {t:"Excited to work with Antaras for our webinar on June 11 where finance teams using...", ty:"Image", r:2, c:1, rp:1},
      {t:"Great Northern Equipment: small team, big efficiency gains. As a leading wholesale...", ty:"Image", r:32, c:0, rp:10},
      {t:"If you are looking to sharpen your approach to finance this April, these virtual...", ty:"Document/carousel", r:8, c:0, rp:0},
      {t:"Finance teams aren't burned out because they work too much. They're burned out...", ty:"Document/carousel", r:15, c:0, rp:0},
      {t:"AP fraud doesn't announce itself. It hides in duplicate invoices and last-minute...", ty:"Article/Link", r:6, c:0, rp:0},
      {t:"The accounts payable process covers a lot of ground: purchase orders, invoice...", ty:"Article/Link", r:13, c:0, rp:3},
      {t:"We are back with a new edition of MediusExplains! Today, we're delving into...", ty:"Document/carousel", r:13, c:1, rp:1},
      {t:"Day 1 at InfoTeamdagene 2026. Always great to be here, catching up with familiar...", ty:"Image", r:28, c:0, rp:0},
      {t:"Two inspiring days at the Future of Finance CFO Exchange in London are coming to a...", ty:"Image", r:40, c:2, rp:3},
      {t:"If fraud prevention and supplier headaches are on your radar, this one's worth your...", ty:"Image", r:10, c:0, rp:1},
      {t:"We had a great time at VISUAL Focus hosted by WM Synergy this week in Las Vegas. It...", ty:"Image", r:40, c:1, rp:3},
      {t:"AI agents. Supplier intelligence. Autonomous finance. In our March webinars, we are...", ty:"Document/carousel", r:17, c:0, rp:3}
    ]},
    { name: "Qvalia", posts: [
      {t:"Peppol for developers: 10 common invoice errors and how to fix them. From recipient...", ty:"Image", r:8, c:0, rp:1},
      {t:"Thank you to everyone who joined today's webinar with Julius Nilsson from Docupath...", ty:"Image", r:29, c:3, rp:3},
      {t:"E-invoicing mandates are becoming infrastructure decisions. As Slovakia prepares for...", ty:"Image", r:5, c:0, rp:1},
      {t:"Slovakia's eFaktura framework is another important step in Europe's transition...", ty:"Image", r:28, c:0, rp:2},
      {t:"Qvalia is now certified for Slovakia e-invoicing under the eFaktura framework. We...", ty:"Image", r:32, c:1, rp:6},
      {t:"Connect is more than digital invoicing. It's your gateway to automation, compliance,...", ty:"Article/Link", r:4, c:1, rp:0},
      {t:"Qvalia's Business Continuity Management System has now been certified against ISO...", ty:"Image", r:6, c:0, rp:1},
      {t:"Qvalia is now listed in the Cloud Security Alliance STAR Registry. It's an...", ty:"Image", r:8, c:1, rp:0},
      {t:"Qvalia is now available on iPhone and Android. Approve invoices in seconds. From...", ty:"Image", r:42, c:5, rp:5},
      {t:"In 2025, we expanded Qvalia's platform across nearly all fronts. Fredrik Forsell...", ty:"Image", r:13, c:1, rp:2},
      {t:"[Peppol for developers] How to get started with Peppol API. Learn how to: Set...", ty:"Image", r:9, c:0, rp:1},
      {t:"Belgium mandates #Peppol e-invoicing for most B2B transactions on January 1,...", ty:"Image", r:9, c:0, rp:1},
      {t:"The 2026 Peppol country guide - full list, status, and coverage map. Learn where...", ty:"Image", r:14, c:0, rp:0},
      {t:"[Upcoming webinar] AI-ready finance with Intelligent Document Processing. AI is...", ty:"Image", r:25, c:0, rp:7},
      {t:"Great day at Qvalia together with our friends from Amazon Web Services (AWS). We...", ty:"Image", r:81, c:3, rp:8}
    ]},
    { name: "AMC Banking", posts: [
      {t:"Working with multiple banks shouldn't mean working with multiple banking processes...", ty:"Text", r:4, c:0, rp:0},
      {t:"What do you learn from 30+ years of working with bank integration? Probably this: No...", ty:"Image", r:18, c:1, rp:1},
      {t:"How many systems does your finance team touch just to make a payment? The ERP. A...", ty:"Article/Link", r:12, c:1, rp:0},
      {t:"Thanks to everybody who showed up for the reception in our new building! We are...", ty:"Image", r:29, c:1, rp:0},
      {t:"AMC Banking operates under Service Provider Agreements with selected banks,...", ty:"Text", r:9, c:0, rp:0},
      {t:"We're moving and we'd love to celebrate with you. Join us for a reception where you...", ty:"Event", r:12, c:0, rp:1},
      {t:"(no text)", ty:"Document/carousel", r:4, c:0, rp:0},
      {t:"Discover our new app designed to simplify and automate cash management directly...", ty:"Video", r:6, c:0, rp:0},
      {t:"Your biggest compliance risk might be a process nobody questions anymore. Not every...", ty:"Article/Link", r:6, c:0, rp:2},
      {t:"In this webinar, we'll take you through how AMC Banking's intelligent cash sweeping...", ty:"Video", r:10, c:0, rp:0},
      {t:"Bank integration: Myth vs reality. Many finance teams treat bank connectivity like a...", ty:"Video", r:11, c:0, rp:3},
      {t:"The AMC Banking webinar series offers: demos, new features, use cases and Q&A,...", ty:"Video", r:10, c:0, rp:1},
      {t:"AMC is expanding and we are currently looking for a java developer. If you could see...", ty:"Article/Link", r:12, c:0, rp:3},
      {t:"Still uploading payment files manually? At some point, it stops scaling. More banks...", ty:"Article/Link", r:6, c:0, rp:0},
      {t:"Before summer kicks off, we wanted to share a small milestone from AMC Banking. We...", ty:"Image", r:13, c:2, rp:2},
      {t:"You can still register for our reception next week if you would like to swing by and...", ty:"Event", r:0, c:0, rp:0},
      {t:"We bought The White House... at Frederiksberg. We are looking forward to moving into...", ty:"Article/Link", r:30, c:3, rp:2},
      {t:"You can still sign up for our webinar tomorrow where we take a deep dive into the...", ty:"Article/Link", r:4, c:0, rp:0},
      {t:"In case you have not yet signed up for our treasury extension webinar about cash...", ty:"Article/Link", r:5, c:0, rp:0},
      {t:"The torch has officially been passed. We're excited to move into Kobenhavns...", ty:"Image", r:56, c:4, rp:1},
      {t:"Enterprise treasury demands structure, visibility, and control. For large...", ty:"Image", r:7, c:0, rp:0},
      {t:"ERP bank integration is rarely 'plug-and-play'. That's why AMC Banking's Consultancy...", ty:"Image", r:23, c:0, rp:0}
    ]},
    { name: "B2Brouter", posts: [
      {t:"Si crees que la factura electronica obligatoria es solo subir un archivo a un...", ty:"Text", r:0, c:0, rp:0},
      {t:"France is only the beginning. For ERP teams, the real challenge isn't adapting to...", ty:"Repost", r:0, c:0, rp:0},
      {t:"Vos clients ne veulent pas changer de logiciel. Ils veulent etre conformes sans...", ty:"Text", r:1, c:0, rp:0},
      {t:"Hito alcanzado: Mas de 18 000 empresas francesas confian en @B2Brouter en la red...", ty:"Image", r:27, c:5, rp:2},
      {t:"Was werden Ihre Kunden 2027 von Ihrer Software erwarten? Seit 2025 mussen...", ty:"Text", r:0, c:0, rp:0},
      {t:"Proximos webinars | Septiembre 2026. Este junio te esperamos en dos sesiones en...", ty:"Image", r:3, c:0, rp:1},
      {t:"Upcoming webinars | September 2026. Want to integrate e-invoicing into your...", ty:"Image", r:2, c:0, rp:2},
      {t:"Diqto s'appuie sur B2Brouter pour la facturation electronique via eDocSync...", ty:"Image", r:9, c:1, rp:2},
      {t:"Nous y sommes. Le 1er septembre 2026 n'est plus une echeance: c'est aujourd'hui...", ty:"Document/carousel", r:8, c:0, rp:1},
      {t:"Comment integrer la facturation electronique a son logiciel sans complexifier...", ty:"Article/Link", r:6, c:2, rp:2},
      {t:"J-5: une facture conforme peut malgre tout echouer si vos donnees clients sont...", ty:"Text", r:4, c:0, rp:1},
      {t:"La facturation electronique n'est que la moitie de la reforme. Avez-vous prepare...", ty:"Document/carousel", r:3, c:4, rp:1},
      {t:"J-7 en France: attendre de voir ce qui se passe n'est plus une strategie. Dans...", ty:"Image", r:11, c:2, rp:4},
      {t:"Ja no hi ha excuses per adoptar la facturacio electronica, queden molt pocs dies i...", ty:"Article/Link", r:20, c:1, rp:2},
      {t:"J-14 avant la reforme: pour les editeurs de logiciels, le dernier moment est...", ty:"Image", r:12, c:7, rp:2},
      {t:"Die E-Rechnung in Deutschland ist bereits Realitat - trotzdem halten sich noch...", ty:"Document/carousel", r:2, c:0, rp:0},
      {t:"B2Brouter talent stands out in London! After one week of learning and just three...", ty:"Image", r:38, c:0, rp:4},
      {t:"Partner Announcement: B2Brouter. We're thrilled to...", ty:"Image", r:10, c:2, rp:3},
      {t:"Le permier Septembre est prochajn!", ty:"Article/Link", r:7, c:1, rp:2},
      {t:"Comment bien choisir sa Plateforme Agreee avant l'entree en vigueur de la...", ty:"Document/carousel", r:6, c:0, rp:1},
      {t:"La reforme francaise de la facturation electronique ne concerne pas seulement la...", ty:"Image", r:9, c:0, rp:1},
      {t:"Germany's e-invoicing rollout is not just a national compliance update. It is part...", ty:"Text", r:8, c:0, rp:1},
      {t:"Belgium's B2B e-invoicing mandate is already in force. Since 1 January 2026,...", ty:"Document/carousel", r:10, c:1, rp:2},
      {t:"Verifactu como el primer paso hacia el despliegue de ViDA, creo que es...", ty:"Article/Link", r:13, c:2, rp:1},
      {t:"Tienes que enviar todas tus facturas a la AEAT? La respuesta rapida es: no...", ty:"Document/carousel", r:5, c:0, rp:2},
      {t:"VeriFactu no es el unico gran cambio que viene en Espana. La Ley Crea y Crece...", ty:"Image", r:0, c:0, rp:0},
      {t:"La reforme fiscale francaise ne se limite pas a \"envoyer des factures...", ty:"Document/carousel", r:14, c:0, rp:4},
      {t:"Meet our Sales Team. They are the people who connect businesses with the right...", ty:"Document/carousel", r:9, c:0, rp:3},
      {t:"Electronic invoicing is accelerating across Europe, and B2Brouter is growing with...", ty:"Article/Link", r:5, c:0, rp:0},
      {t:"La factura electronica no va solo de enviar una factura en formato digital. Con la...", ty:"Document/carousel", r:2, c:0, rp:1},
      {t:"2026 e-invoicing reality check: is your business ready? Across Europe, APAC and...", ty:"Poll", r:2, c:0, rp:2},
      {t:"La solucion publica de facturacion electronica de la AEAT sera una pieza...", ty:"Document/carousel", r:9, c:1, rp:0},
      {t:"Empfangen ist nicht gleich Verarbeiten. Genau daruber haben wir vor zwei Wochen eine...", ty:"Document/carousel", r:4, c:0, rp:0},
      {t:"El otro dia Aleix Gasset se atrevio a explicarnos en un video de dos minutos que es...", ty:"Article/Link", r:4, c:0, rp:0},
      {t:"Vous facturez deja des administrations, hopitaux, collectivites ou organismes...", ty:"Document/carousel", r:6, c:0, rp:2},
      {t:"ERP & E-Invoicing Integration Partners - Monthly Ranking Status | July 2026. The...", ty:"Image", r:47, c:3, rp:8},
      {t:"La factura electronica es una herramienta para que Hacienda lo vea todo? Esta es...", ty:"Document/carousel", r:10, c:2, rp:1},
      {t:"Electronic invoicing is no longer just about tax compliance, it's about data...", ty:"Document/carousel", r:5, c:0, rp:1},
      {t:"La reforme de la facturation electronique en France ne se limite pas a choisir une...", ty:"Article/Link", r:8, c:0, rp:4},
      {t:"A few days ago, B2Brouter attended Peppol Conference Europe 2026 in Brussels...", ty:"Image", r:15, c:0, rp:2},
      {t:"VeriFactu, Ley Crea y Crece, factura electronica B2B... demasiados conceptos y una...", ty:"Document/carousel", r:11, c:0, rp:1},
      {t:"Capde - says it exactly right: France's e-invoicing reform is not just about sending...", ty:"Image", r:3, c:0, rp:2},
      {t:"Peppol is becoming one of the most reliable ways to exchange B2B invoices...", ty:"Document/carousel", r:10, c:0, rp:1},
      {t:"Plateformes SaaS juridiques en France: 2026 n'est pas seulement une echeance de...", ty:"Document/carousel", r:7, c:0, rp:1},
      {t:"Germany's B2B e-invoicing roadmap is already moving. German businesses must be...", ty:"Document/carousel", r:11, c:2, rp:1},
      {t:"Crees que Ley Crea y Crece y VeriFactu son lo mismo? Spoiler: no. Confundirlas...", ty:"Document/carousel", r:8, c:0, rp:1},
      {t:"In 8 days, B2Brouter will be attending Peppol Conference Europe 2026 in Brussels...", ty:"Text", r:6, c:0, rp:2},
      {t:"Testing should not feel risky. With B2Brouter Sandbox, developers and technical...", ty:"Document/carousel", r:5, c:0, rp:3},
      {t:"Meet our Business Operations team. They are the people behind many of the areas...", ty:"Document/carousel", r:5, c:1, rp:2},
      {t:"La factura electronica obligatoria ya tiene marco regulatorio, pero todavia quedan...", ty:"Article/Link", r:5, c:0, rp:0}
    ]},
    { name: "Dooap", posts: [
      {t:"We are hitting the road in a few weeks and headed to Dynamics User Group (DUG)...", ty:"Image", r:12, c:2, rp:1},
      {t:"Evaluating AP automation for Microsoft Dynamics 365 Finance? The shortlist gets...", ty:"Article/Link", r:9, c:0, rp:1},
      {t:"Dooap Studio has a new home: dooapstudio.ai. It's our agentic AI automation...", ty:"Image", r:9, c:1, rp:6},
      {t:"Sharing our story of Dooap Studio live from Dynamic Communities AI Business...", ty:"Video", r:26, c:2, rp:4},
      {t:"Well, that's a wrap on DynamicsMinds. The Dooap team is heading back through time...", ty:"Image", r:70, c:4, rp:0},
      {t:"With AP you have a lot of balls in the air at all times, let Dooap help you herd...", ty:"Image", r:57, c:1, rp:2},
      {t:"We're heading to #DynamicsCon in Las Vegas next week! If you're attending, be sure...", ty:"Image", r:24, c:1, rp:3},
      {t:"Just think of the possibilities with Dooap Studio! Here's one for you.", ty:"Image", r:14, c:0, rp:1},
      {t:"We're sponsoring Dynamics User Group (DUG) DynamicsCon Regional: Ohio Valley on...", ty:"Image", r:9, c:1, rp:1},
      {t:"We are here and you can find the team and table next to registration. Come chat with...", ty:"Video", r:24, c:2, rp:0},
      {t:"Still herding invoices manually? What if your AP process could herd itself? Join...", ty:"Image", r:32, c:0, rp:2},
      {t:"Excited to introduce our latest Dooap Unleashed: Run With Us - Eftsure! Scott...", ty:"Video", r:39, c:2, rp:1},
      {t:"This is what agentic AP automation looks like. Dooap Studio gives AP teams the power...", ty:"Video", r:17, c:0, rp:6},
      {t:"Everyone is talking about AI in finance. Very few are talking about what's actually...", ty:"Image", r:6, c:1, rp:1},
      {t:"Join us at the Dynamic Communities Summit NA Roadshow in Vancouver. Built...", ty:"Image", r:16, c:0, rp:3},
      {t:"The biggest problem in finance isn't the system. It's that nobody trusts it. That's...", ty:"Video", r:21, c:3, rp:1},
      {t:"Sam Bush live here in Helsinki. The Dooap team is gearing up for DynamicsMinds next...", ty:"Video", r:66, c:4, rp:0},
      {t:"Run AP with AI agents. Not manual work. Today we're launching Dooap Studio - Agentic...", ty:"Video", r:46, c:6, rp:8},
      {t:"Welcome to Dooap Unleashed. A video series coming to your LinkedIn life all about...", ty:"Video", r:15, c:2, rp:2},
      {t:"What message would you send to the future? We took DynamicsMinds' \"Message to the...", ty:"Video", r:40, c:15, rp:1},
      {t:"AI is no longer \"coming\" to AP. It's redefining how finance teams lead, work, and...", ty:"Document/carousel", r:10, c:1, rp:2},
      {t:"Every AP Manager knows this feeling: you spot the fix, but IT has a three-week...", ty:"Article/Link", r:11, c:0, rp:3},
      {t:"Looking forward to sharing more about Dooap Studio this week at AI Business Solutions...", ty:"Video", r:19, c:0, rp:0},
      {t:"Five years in, and she still says it feels new every day. In this episode of Dooap...", ty:"Image", r:18, c:1, rp:0},
      {t:"Who is attending Dynamic Communities's AI Business Solutions Partner Executive...", ty:"Image", r:30, c:4, rp:1},
      {t:"Every D365 vendor is racing to say \"agentic\" right now. Most are still figuring out...", ty:"Image", r:19, c:1, rp:4},
      {t:"Invoice approvals shouldn't be a treasure hunt. With Dooap, your workflows adapt to...", ty:"Video", r:10, c:0, rp:2},
      {t:"Transform your AP process with automation built for Dynamics 365 Finance. Capture...", ty:"Article/Link", r:15, c:0, rp:0},
      {t:"What does AI literacy actually look like for a Dynamics 365 Finance team in 2026?...", ty:"Article/Link", r:10, c:0, rp:1},
      {t:"PO matching is one of those tasks you can't ignore, but you definitely don't want to...", ty:"Video", r:13, c:0, rp:1},
      {t:"Great AP automation happens before you even know it. Dooap handles it quietly in the...", ty:"Video", r:16, c:0, rp:1},
      {t:"Last time we said \"something new is coming,\" we introduced Dooap Studio - agentic AP...", ty:"Image", r:25, c:0, rp:3},
      {t:"If you ask us what one word we'd like to hear to describe Dooap - it's \"easy\". Great...", ty:"Video", r:9, c:1, rp:3},
      {t:"Approving invoices shouldn't keep you tied to your desk. With the Dooap AP...", ty:"Article/Link", r:10, c:1, rp:3},
      {t:"Thank you, Ellipse Solutions, for the highlight. We're proud of our collaboration,...", ty:"Image", r:6, c:0, rp:0},
      {t:"Somewhere right now, an AP manager is refreshing their inbox hoping an approval...", ty:"Image", r:18, c:0, rp:2},
      {t:"Great conversations. Great community.", ty:"Video", r:9, c:1, rp:0},
      {t:"The Dynamics community is coming to Toronto - and so are we. Dynamics User Group...", ty:"Image", r:16, c:0, rp:1},
      {t:"Love spending time with our partners all year around. At Dynamics User Group (DUG)...", ty:"Video", r:9, c:0, rp:2},
      {t:"Thanks again Dynamic Communities for the opportunity to showcase our #APautomation...", ty:"Image", r:4, c:0, rp:0},
      {t:"Set up and ready for \"Herd your AP with AI Agents\", in Sunset on level 11. Come join...", ty:"Image", r:28, c:2, rp:3},
      {t:"We're heading to #DynamicsMinds2026 and looking forward to being back with the...", ty:"Image", r:30, c:0, rp:1},
      {t:"Considering AP Automation for D365 Finance or BC? Maybe you did not have a chance to...", ty:"Article/Link", r:9, c:0, rp:2},
      {t:"AI is inevitably transforming Accounts Payable. Read how our Chief Product Officer...", ty:"Article/Link", r:11, c:0, rp:2},
      {t:"We're on a tasty streak! Check out our new customers from the food and beverage...", ty:"Article/Link", r:0, c:0, rp:0},
      {t:"The AP world is about to change. 5 days. #AccountsPayable #D365Finance Microsoft", ty:"Image", r:21, c:6, rp:2},
      {t:"Something new is coming. Stay tuned. #dooapunleashed", ty:"Image", r:20, c:1, rp:4},
      {t:"Our #APautomation solution is designed for Microsoft #D365FO, and a widespread and...", ty:"Document/carousel", r:4, c:0, rp:0},
      {t:"We are here and ready to talk about AI and AP for Dynamics 365 Finance in Tampa for...", ty:"Image", r:49, c:3, rp:0},
      {t:"AI is changing Accounts Payable. But control still matters. At the Dynamic...", ty:"Image", r:14, c:3, rp:2}
    ]},
    { name: "Yavrio", posts: [
      {t:"A massive thank you to everyone in the ERP + Fintech community who made the Yavrio...", ty:"Image", r:65, c:7, rp:1},
      {t:"Meet James Pike, one of our Partner Success Managers at Yavrio! James sits where the...", ty:"Image", r:48, c:2, rp:0},
      {t:"An embedded payments system means more than operational efficiency. It means your...", ty:"Video", r:12, c:0, rp:2},
      {t:"The Yavrio team is already counting down the days till Directions for Enterprise...", ty:"Image", r:29, c:0, rp:0},
      {t:"Our team just touched down in Ohio and we can't wait to meet with our partners and...", ty:"Image", r:28, c:4, rp:0},
      {t:"What a day. The whole UK team got together in Paddington to celebrate the launch...", ty:"Image", r:84, c:11, rp:1},
      {t:"This week we've been celebrating the return of Samantha Felling to our USA partner...", ty:"Image", r:32, c:2, rp:1},
      {t:"More than 5 billion Direct Debit payments run through the UK's Bacs network every...", ty:"Image", r:33, c:2, rp:2},
      {t:"What does success actually look like when banking is fully integrated into the ERP?...", ty:"Video", r:35, c:2, rp:2},
      {t:"Yavrio x Wenalyze. We're building smarter fraud prevention into Yavrio - helping...", ty:"Image", r:21, c:2, rp:0},
      {t:"A brilliant afternoon at Fortnum & Mason, bringing together senior retail leaders...", ty:"Image", r:72, c:7, rp:3},
      {t:"8-10 days. That's the average close when statements are still pulled manually. 3...", ty:"Document/carousel", r:13, c:1, rp:2},
      {t:"Cards on the Table. The launch of Yavrio Cards called for a proper celebration,...", ty:"Image", r:49, c:11, rp:2},
      {t:"We are live now with Western Computer for our joint session on banking in Microsoft...", ty:"Text", r:9, c:0, rp:0},
      {t:"For finance teams still importing bank statements by CSV into Microsoft Dynamics 365...", ty:"Document/carousel", r:15, c:0, rp:1},
      {t:"What a 2026 Yavrio is having so far! It's hard to believe we're nearly halfway...", ty:"Image", r:110, c:9, rp:0},
      {t:"DynamicsMinds 2026 is done and what a week it's been. Over the last few days,...", ty:"Image", r:108, c:5, rp:0},
      {t:"Day one of DynamicsMinds wrapped and what a start its been. Our team, Margaret...", ty:"Image", r:82, c:4, rp:0},
      {t:"DynamicsCon 2026 wrapped and what a few days it was! A hot week in Vegas as sponsors...", ty:"Image", r:55, c:2, rp:0},
      {t:"We're excited to have our feet on the ground at Directions ASIA 2026 in Vietnam!...", ty:"Image", r:68, c:1, rp:1},
      {t:"Another amazing event. Yavrio had an incredible time at this year's Node4...", ty:"Image", r:65, c:2, rp:0},
      {t:"\"That's a wrap on Directions North America 2026\". It's been a great few days in...", ty:"Image", r:64, c:7, rp:0},
      {t:"A full day in for the Yavrio team and it's already been a strong start at Directions...", ty:"Image", r:86, c:2, rp:0},
      {t:"Meet Phillip Dawson, our VP Sales & Partnerships! Phil has been at the heart of...", ty:"Image", r:64, c:8, rp:0},
      {t:"Microsoft's Tier 1 ERP now has modern bank connectivity, embedded payments and...", ty:"Image", r:40, c:5, rp:0},
      {t:"Still moving bank data into your finance system one CSV at a time? It may be time...", ty:"Video", r:27, c:0, rp:1},
      {t:"We're live at Directions Spanish BC Day and what a fantastic day it's been so...", ty:"Image", r:23, c:0, rp:0},
      {t:"Four years ago, we launched Yavrio Banking and set out on a mission to create a way...", ty:"Image", r:105, c:26, rp:6},
      {t:"Great to be part of HSO's Customer Day! We had a fantastic day last month...", ty:"Image", r:28, c:1, rp:2},
      {t:"Yavrio Out and About - This Week! It's been a whirlwind week for the Yavrio...", ty:"Image", r:66, c:3, rp:0},
      {t:"Hello from a roasting Las Vegas. I'm at #DynamicsCon2026 this week where we've...", ty:"Image", r:99, c:10, rp:1},
      {t:"Finance teams BEFORE vs AFTER Yavrio. Before Yavrio: manual bank files,...", ty:"Video", r:48, c:5, rp:0},
      {t:"Bank connectivity and payments are becoming a bigger part of the Business Central...", ty:"Video", r:25, c:3, rp:2},
      {t:"It was great to attend the Dynamics 365 & Power Platform User Group National event...", ty:"Image", r:55, c:3, rp:1},
      {t:"The pace of technological change in financial services isn't slowing, and leadership...", ty:"Image", r:50, c:4, rp:0},
      {t:"This week some of our team were lucky enough to attend the Microsoft #AITourLondon...", ty:"Image", r:66, c:0, rp:0},
      {t:"After a few not-so-subtle hints, it's time to make it official... We've moved...", ty:"Image", r:179, c:34, rp:3},
      {t:"We're upgrading our London HQ! The same Yavrio energy, but now with much more room...", ty:"Image", r:97, c:30, rp:3},
      {t:"This summer we're opening up our London Paddington office for the first ever Yavrio...", ty:"Image", r:49, c:8, rp:5},
      {t:"We're excited to welcome Samuel Price as a Sales Consultant as we continue expanding...", ty:"Image", r:49, c:9, rp:1},
      {t:"Reflecting on our company off site to wrap up the year, the Yavrio crew got together...", ty:"Image", r:72, c:8, rp:0},
      {t:"We're excited to be hosting an exclusive roundtable with Microsoft and iLink...", ty:"Image", r:32, c:3, rp:0},
      {t:"Big milestone for Yavrio! Today we're launching Yavrio Cards: A cards payment...", ty:"Video", r:145, c:25, rp:9},
      {t:"We were delighted to welcome Tim Chong, Co-founder and CEO of Yonder, join us at our...", ty:"Image", r:80, c:9, rp:0},
      {t:"This week at Yavrio! Partner events, customers catch ups, brainstorming and some big...", ty:"Video", r:56, c:6, rp:1},
      {t:"Today, we're launching Yavrio Cards: A cards payment solution fully embedded inside...", ty:"Image", r:131, c:9, rp:5},
      {t:"Yavrio - Open Banking is the multi award-winning banking integration for Microsoft...", ty:"Image", r:11, c:0, rp:5},
      {t:"Reflecting on an incredible week in Poland. We're still buzzing from Directions EMEA...", ty:"Image", r:74, c:12, rp:1},
      {t:"Day 2 at Community Summit 2025 is underway! Over 5,000 attendees have gathered...", ty:"Image", r:43, c:6, rp:1},
      {t:"Meet our Head of UK Sales, Charlotte Huang! Charlotte has led our UK sales team...", ty:"Image", r:176, c:5, rp:0}
    ]},
    { name: "Rillion", posts: [
      {t:"Our CFO to CFO newsletter is live! This is a new initiative from our CFO, Johan...", ty:"Image", r:6, c:0, rp:0},
      {t:"One picture. Seven people. 150+ years of Rillion experience. That's a lot of...", ty:"Image", r:105, c:14, rp:2},
      {t:"The numbers we didn't show you. We asked 250 U.S. finance leaders how AI is actually...", ty:"Document/carousel", r:14, c:3, rp:2},
      {t:"Some things belong in a museum. Manual invoice entry is one of them. Copying invoice...", ty:"Image", r:10, c:0, rp:0},
      {t:"Turns out our Product team is fast in more ways than one. Last week, Team...", ty:"Video", r:23, c:1, rp:0},
      {t:"I recently had the opportunity to share my perspective on AI in finance for...", ty:"Article/Link", r:132, c:7, rp:5},
      {t:"Did you know that most finance leaders expect AI to significantly change the finance...", ty:"Image", r:13, c:1, rp:0},
      {t:"Don't miss the LinkedIn Live we're hosting today. AI adoption in finance is moving...", ty:"Image", r:14, c:1, rp:0},
      {t:"68% of finance teams use AI every day. 39% of CFOs trust it to act on its own...", ty:"Image", r:26, c:2, rp:2},
      {t:"Launch day. We just published the US edition of Rillion's 2026 AI in Finance...", ty:"Image", r:27, c:6, rp:1},
      {t:"250 US finance leaders told us how they're using AI. And the numbers don't tell the...", ty:"Document/carousel", r:19, c:2, rp:10},
      {t:"250 U.S. CFOs told us what they really think about AI. Now we're bringing the debate...", ty:"Image", r:14, c:0, rp:2},
      {t:"2029. How many tasks in finance will still be done by humans? Finance leaders expect...", ty:"Video", r:12, c:2, rp:0},
      {t:"Dry run mode: ON. The studio is getting ready. The slides are getting their final...", ty:"Video", r:30, c:3, rp:5},
      {t:"The Finance AI Illusion... What is it? And is your finance team caught in it? We are...", ty:"Image", r:24, c:3, rp:7},
      {t:"Is there a gap between how ready finance leaders think they are for AI and what the...", ty:"Video", r:24, c:3, rp:3},
      {t:"Another G2 badge drop we're extremely proud to be part of. As always, a huge shoutout...", ty:"Video", r:35, c:4, rp:7},
      {t:"Have you seen the latest OnlyCFO newsletter? We have and we're excited to see...", ty:"Image", r:14, c:3, rp:4},
      {t:"\"I love my Excel sheets.\" Sean Milmoe, CFO & Co-Founder at 360 Energy, isn't alone -...", ty:"Video", r:21, c:0, rp:2},
      {t:"If AI is already part of your team's daily workflow... this poll probably isn't for...", ty:"Poll", r:6, c:0, rp:3},
      {t:"AP teams, here's your mid-vacation reminder. (If you're checking your inbox from...", ty:"Document/carousel", r:8, c:0, rp:1},
      {t:"Many finance leaders worry AI will make mistakes they can't track. Rasmus Areskoug,...", ty:"Text", r:13, c:2, rp:0},
      {t:"Denmark leads AI adoption in the Nordics. Sweden lags behind. But Olli Saksa, CFO at...", ty:"Text", r:6, c:0, rp:0},
      {t:"80% of finance leaders use AI daily, but only 1 in 5 trust it for strategic...", ty:"Text", r:8, c:3, rp:1},
      {t:"OCR vs AI invoice capture: what's the actual difference for AP automation? If your...", ty:"Document/carousel", r:15, c:1, rp:3},
      {t:"72% of finance teams still struggle with manual corrections despite investing in AI...", ty:"Text", r:36, c:1, rp:2},
      {t:"If you'd told us our favourite team events would be the ones you can track on...", ty:"Image", r:19, c:0, rp:0},
      {t:"48% of finance leaders say they want to be strategic advisors. So why do investments...", ty:"Text", r:8, c:0, rp:0},
      {t:"If you're not optimizing your vacation as much as your AP processes... we need to...", ty:"Document/carousel", r:10, c:0, rp:0},
      {t:"Finance teams aren't slow to adopt AI, we just doesn't have the luxury of...", ty:"Video", r:16, c:1, rp:1},
      {t:"While most finance leaders are still figuring out where AI fits, Peter Egehoved, CFO...", ty:"Text", r:58, c:8, rp:0},
      {t:"What's possible today wasn't possible 6 months ago. For finance leaders to succeed...", ty:"Image", r:45, c:3, rp:4},
      {t:"The ERP you choose today can either accelerate your next 10 years... or slow them...", ty:"Video", r:11, c:0, rp:2},
      {t:"While everyone's drowning in opinions on where AI belongs in finance, Monika Pers,...", ty:"Text", r:12, c:1, rp:0},
      {t:"If your finance team only talks to finance, you're leaving value on the table. The...", ty:"Video", r:12, c:1, rp:1},
      {t:"We asked 250 CFOs across the Nordics about AI in finance. Then put our own CFO Johan...", ty:"Document/carousel", r:9, c:0, rp:0},
      {t:"The Nordic AI Finance Report had zero shortage of \"mic-drop\" quotes but this one...", ty:"Text", r:7, c:0, rp:0},
      {t:"Nail your ERP and CRM and you're 90% there - that used to be the rule for finance...", ty:"Video", r:8, c:1, rp:0},
      {t:"26% of CFOs say lack of AI competence is the single biggest barrier to broader...", ty:"Text", r:18, c:1, rp:1},
      {t:"Our marketing team swapped their laptops for race bibs yesterday - running...", ty:"Image", r:35, c:3, rp:1},
      {t:"Rillion AI Day - LFG. On Monday, we put work aside and got our team together for a...", ty:"Image", r:40, c:4, rp:0},
      {t:"What's the best place to start with AI in finance? The small yes/no decisions you're...", ty:"Video", r:14, c:2, rp:1},
      {t:"250 CFOs across Sweden, Denmark and Finland told us where AI in finance *actually*...", ty:"Document/carousel", r:19, c:8, rp:3},
      {t:"[searching...] I'm on the hunt for a US native CFO or financial executive based...", ty:"Text", r:33, c:22, rp:4},
      {t:"AI transformation in finance is more about getting your people onboard than it is...", ty:"Video", r:31, c:3, rp:5},
      {t:"If you think AI will eliminate entry-level roles in finance, here's a fresh take on...", ty:"Document/carousel", r:22, c:1, rp:1},
      {t:"Rillion + Stratas: taking AP automation in the UK to the next level. We're...", ty:"Video", r:23, c:2, rp:2},
      {t:"Just got back from two of the most energizing days I've had in a long time!...", ty:"Image", r:52, c:8, rp:1},
      {t:"Sage Intacct users, this one's for you! Rillion now has a new integration with...", ty:"Document/carousel", r:23, c:2, rp:5},
      {t:"We made it into Dagens Industri today with the insights from our Nordic Finance AI...", ty:"Image", r:120, c:5, rp:1}
    ]},
    { name: "Fidesic", posts: [
      {t:"Your AP automation was supposed to eliminate manual work. Instead your team is still...", ty:"Image", r:0, c:0, rp:0},
      {t:"Rally Day is coming to Nashville on Sunday, October 11, a Knights of GP event built...", ty:"Image", r:7, c:2, rp:1},
      {t:"Checks are still the top target for payment fraud according to the 2026 AFP Payments...", ty:"Image", r:1, c:0, rp:0},
      {t:"#MySummitNA", ty:"Image", r:0, c:0, rp:0},
      {t:"How to Spot AP Bottlenecks Before Growth Stalls. Warning signs your AP process won't...", ty:"Image", r:1, c:0, rp:0},
      {t:"Cash flow is a fact. Profit is an opinion. #WednesdayWisdom #AccountsPayable", ty:"Image", r:1, c:0, rp:0},
      {t:"Did you know 8 days is how long the median finance team spends closing the books...", ty:"Image", r:1, c:0, rp:0},
      {t:"Ready to rock 'n' roll in Nashville for Dynamic Communities Summit NA 2026? We're...", ty:"Image", r:2, c:0, rp:1},
      {t:"In this post highlight some of the common bottlenecks that hinder scalability so you...", ty:"Article/Link", r:0, c:0, rp:0},
      {t:"Like any large financial data migration, you can expect a migration from Dynamics GP...", ty:"Article/Link", r:2, c:0, rp:0},
      {t:"#LoveFriday #LoveAutomation", ty:"Image", r:0, c:0, rp:0},
      {t:"Payment behavior directly affects cash flow, supplier relationships, and access to...", ty:"Article/Link", r:1, c:0, rp:0},
      {t:"Fidesic has been named Best Of AP Automation Tools for Dynamics ERP in 2026 by ERP...", ty:"Article/Link", r:7, c:0, rp:1},
      {t:"\"Discipline in accounts payable is discipline in cash flow.\" #WednesdayWisdom #APTeam", ty:"Image", r:0, c:0, rp:0},
      {t:"This post removes some of the fear around GP end of support and offers practical...", ty:"Article/Link", r:2, c:0, rp:0},
      {t:"It's comin' up quick! Looking forward to seeing everyone in Nashville for...", ty:"Image", r:6, c:2, rp:1},
      {t:"Fidesic is continually renewing focus on building trust in the Dynamics Community...", ty:"Text", r:1, c:0, rp:0},
      {t:"Unsurprisingly, not all AI projects are a success. At Fidesic, we mitigate your risk...", ty:"Image", r:1, c:0, rp:0},
      {t:"Fidesic has been recognized as a High Performer on G2, and the team could not be...", ty:"Article/Link", r:1, c:0, rp:0},
      {t:"This post covers what BC handles natively for PO matching and AP automation, where...", ty:"Article/Link", r:0, c:0, rp:0},
      {t:"Is running accounts payable out of Business Central missing something? AP getting in...", ty:"Article/Link", r:3, c:0, rp:0},
      {t:"Still on Dynamics GP? Fidesic has deployable AI agents for your Accounts Payable...", ty:"Video", r:7, c:3, rp:0},
      {t:"Kevin Pritchard talks about why we're pumped to part of Knights of GP and what that...", ty:"Video", r:17, c:8, rp:2},
      {t:"Fidesic delivers value beyond AP automation. Don't get us wrong, our software is the...", ty:"Video", r:6, c:1, rp:1},
      {t:"Fidesic has officially joined Knights of GP, and we could not be more excited about...", ty:"Image", r:17, c:2, rp:3},
      {t:"Ninety-five percent (95%) of enterprise generative AI pilots fail to deliver any...", ty:"Video", r:9, c:1, rp:2},
      {t:"Last day of Directions NA. Last Fidesic Yeti tumbler! Who's going to get it?...", ty:"Image", r:5, c:0, rp:1},
      {t:"Attending Directions NA? Stop by booth E14 and pick up some cozy socks!...", ty:"Image", r:2, c:0, rp:0},
      {t:"Remittance vs. Bank Transfer: Key Differences. These two terms are sometimes used...", ty:"Image", r:0, c:0, rp:0},
      {t:"\"Every invoice tells a story. Make sure yours check out.\" #WednesdayWisdom #AP", ty:"Image", r:0, c:0, rp:0},
      {t:"Fidesic has been named Best Of AP Automation Tools for Dynamics ERP in 2026 by ERP...", ty:"Article/Link", r:7, c:0, rp:1},
      {t:"Fidesic is the strongest AP automation choice for organizations running Microsoft...", ty:"Article/Link", r:0, c:0, rp:0},
      {t:"There is no secret path to a frictionless ERP migration. But having the right AP...", ty:"Text", r:2, c:1, rp:0},
      {t:"In this post we are going to assume that you know the pain points of manual paper...", ty:"Article/Link", r:0, c:0, rp:0},
      {t:"The right AP automation software enables small accounting departments to manage...", ty:"Article/Link", r:2, c:0, rp:0},
      {t:"Accounts Payable Stats Worth Watching in 2026. Do these numbers hold any interest...", ty:"Document/carousel", r:2, c:1, rp:1},
      {t:"I'm a little late to the Linkedin party on this one, but I did want to recap my time...", ty:"Image", r:35, c:5, rp:1},
      {t:"Who to see at #DirectionsNA? Here's 4 ideas: -Data Courage for advanced analytics...", ty:"Image", r:55, c:3, rp:1},
      {t:"Trying to decide what your next ERP platform will be after Microsoft Dynamics GP?...", ty:"Image", r:4, c:0, rp:1},
      {t:"Stop by the booth and say Hi! Booth E14. #MyDirectionsNA #BusinessCentral", ty:"Image", r:18, c:0, rp:2},
      {t:"Trust isn't something you can claim. It's something you have to earn, over and over,...", ty:"Article/Link", r:0, c:0, rp:0},
      {t:"For startups/SMBs seeking a fully managed AP process w/ minimal internal work,...", ty:"Image", r:3, c:0, rp:0},
      {t:"It's hard to believe we are almost two weeks away from #DirectionsNA. I'm looking...", ty:"Image", r:21, c:3, rp:1},
      {t:"If you are wondering how to set up your purchase order matching, keep in mind, most...", ty:"Article/Link", r:1, c:0, rp:0},
      {t:"Modern AI-based invoice capture uses machine learning models trained on millions of...", ty:"Article/Link", r:0, c:0, rp:0},
      {t:"Fidesic is the strongest AP automation choice for organizations running Microsoft...", ty:"Article/Link", r:1, c:0, rp:0},
      {t:"What separates a successful agentic accounting project from one that fails to...", ty:"Image", r:1, c:0, rp:0},
      {t:"#FunFactFriday ACH is the largest single B2B payment method by transaction value and...", ty:"Image", r:1, c:0, rp:0},
      {t:"Let's talk about something that's been hiding in plain sight in Dynamics GP that...", ty:"Article/Link", r:0, c:0, rp:0},
      {t:"Some strategies sit firmly within AP's direct control. These include capturing early...", ty:"Image", r:0, c:0, rp:0}
    ]},
    { name: "Tipalti", posts: [
      {t:"Arthur Laykin studied philosophy at Tel Aviv University, took a part-time job at the...", ty:"Image", r:2, c:0, rp:0},
      {t:"Scaling globally exposes every crack in your financial infrastructure before it...", ty:"Image", r:2, c:0, rp:0},
      {t:"Chasing down W-9s is nobody's idea of a good time. Tipalti's Tax Form Scan Agent...", ty:"Image", r:3, c:0, rp:0},
      {t:"Take us out to the ball game! The Tipalti Foster City team gathered their popcorn...", ty:"Image", r:76, c:4, rp:3},
      {t:"The Tipalti team was at the World Finance Forum in London this week. Travis Hughson,...", ty:"Image", r:49, c:2, rp:1},
      {t:"Our E-commerce playbook is here! As E-commerce grows, AP complexity grows with it...", ty:"Image", r:4, c:1, rp:0},
      {t:"Custom Ink was processing 1,260 invoices a month across four entities with a team...", ty:"Document/carousel", r:6, c:0, rp:0},
      {t:"Getting buy-in for finance automation is harder than it should be. We've created a...", ty:"Video", r:8, c:1, rp:1},
      {t:"Tipalti Expenses automates approvals, reconciliation, and reimbursements to simplify...", ty:"Text", r:4, c:0, rp:0},
      {t:"League One Volleyball (LOVB) felt stuck with their legacy system. They needed...", ty:"Document/carousel", r:3, c:1, rp:1},
      {t:"Who enjoys PO matching? It's arduous, leads to bottlenecks, and any matching errors...", ty:"Image", r:14, c:0, rp:1},
      {t:"Do you know what a sunny Summer day in Vancouver calls for? A team picnic on the...", ty:"Image", r:98, c:8, rp:3},
      {t:"Before he was a product manager, Yacov Gorovoy was a lawyer. He never coded. When a...", ty:"Image", r:41, c:3, rp:0},
      {t:"20 weeks of AP work, eliminated. Every year. That's what happened when Centerfield...", ty:"Document/carousel", r:7, c:0, rp:1},
      {t:"Tipalti has officially been named to the Inc. 5000 list for nine consecutive years...", ty:"Image", r:190, c:4, rp:3},
      {t:"The trouble with global growth begins when you add country number 2. Now you have to...", ty:"Video", r:3, c:2, rp:0},
      {t:"A company needs to pay a supplier in Germany, a creator in Brazil, and a contractor...", ty:"Image", r:5, c:2, rp:1},
      {t:"Great engineering leadership isn't just about technical expertise; it's about...", ty:"Image", r:4, c:1, rp:1},
      {t:"When Prodege's partner network grew, so did the operational complexity behind every...", ty:"Video", r:12, c:1, rp:0},
      {t:"AI is no longer a \"someday\" conversation in finance. It's a \"now\" conversation. In...", ty:"Image", r:17, c:0, rp:0},
      {t:"Hear directly from finance leaders at AG1, Lantern Community Services, and Lendable...", ty:"Video", r:10, c:0, rp:0},
      {t:"New from the Tipalti Product Team. Most product teams assume you need an...", ty:"Image", r:101, c:5, rp:0},
      {t:"What does it actually take to build financial infrastructure for a company scaling...", ty:"Image", r:7, c:0, rp:0},
      {t:"David Fractor, CFO at ImaginAb, has spent seven years building a finance function...", ty:"Image", r:9, c:0, rp:0},
      {t:"The Tipalti C-Suite were in Vancouver last week for their executive QBR, and they...", ty:"Image", r:128, c:3, rp:2},
      {t:"Tipalti Mass Payments manages the full payout lifecycle in one platform: payee...", ty:"Text", r:22, c:0, rp:2},
      {t:"Technology alone won't make finance more scalable. The biggest gains come from...", ty:"Image", r:7, c:0, rp:0},
      {t:"We are thrilled to share that Tipalti has been named to the Inc. 5000 list for the...", ty:"Image", r:51, c:1, rp:9},
      {t:"Most finance teams using AI today are using it as a faster way to do things they...", ty:"Article/Link", r:31, c:0, rp:0},
      {t:"Tipalti Accounts Payable connects the full AP lifecycle in one system: invoice...", ty:"Text", r:7, c:0, rp:0},
      {t:"In his latest for the Forbes Tech Council, Tipalti CPTO Roby Baruch discusses how AI...", ty:"Article/Link", r:1, c:0, rp:0},
      {t:"Skillshare has 5 million members and a global network of instructors and influencers...", ty:"Document/carousel", r:12, c:0, rp:0},
      {t:"I'm excited to share that Tipalti has been named on CNBC's World's Top FinTech...", ty:"Image", r:52, c:2, rp:6},
      {t:"A hypothetical about manual processes. A vendor submits the same invoice twice,...", ty:"Text", r:6, c:1, rp:0},
      {t:"Ask any finance team that's made the switch to automation what they regret. It's...", ty:"Text", r:2, c:0, rp:0},
      {t:"Paying 50 payees is a task. Paying 5,000 requires a system. Tipalti is that system.", ty:"Text", r:15, c:0, rp:2},
      {t:"Adding a new country doesn't add one new problem. It adds several at once:...", ty:"Video", r:8, c:0, rp:1},
      {t:"81% of organizations say their external partner networks are vital to business...", ty:"Video", r:7, c:0, rp:1},
      {t:"Even the best partner programs lose talent when payments are slow, complicated, or...", ty:"Video", r:8, c:1, rp:1},
      {t:"The Tipalti team is heading to Minneapolis for the Dynamics Community Summit...", ty:"Video", r:6, c:0, rp:0},
      {t:"Today, Tipalti's US offices are closed in observance of Juneteenth - a day that...", ty:"Image", r:37, c:1, rp:1},
      {t:"We had a great time at the #WorldFinanceForum in Amsterdam this week. The team...", ty:"Image", r:47, c:2, rp:1},
      {t:"Manual payment processes don't scale. They just create more manual payments.", ty:"Text", r:10, c:0, rp:0},
      {t:"The finance function is being asked to operate at a higher level. The problem is the...", ty:"Video", r:41, c:0, rp:1},
      {t:"At some point, 'this is how we've always done it' stops being a reason and starts...", ty:"Text", r:3, c:0, rp:0},
      {t:"NEW RESEARCH: The payout infrastructure gap is costing businesses their top...", ty:"Video", r:24, c:0, rp:3},
      {t:"We were proud to sponsor the Spring 2026 CFO Leadership Conference in Boston last...", ty:"Image", r:82, c:6, rp:3},
      {t:"We're on the floor at Affiliate Summit East in New York today and tomorrow. If...", ty:"Video", r:9, c:0, rp:0},
      {t:"Global payouts shouldn't require a global headache.", ty:"Text", r:3, c:0, rp:0},
      {t:"Tipalti is heading to Affiliate Summit East in New York, July 27-28. If your team is...", ty:"Video", r:7, c:0, rp:1}
    ]},
    { name: "Stampli", posts: [
      {t:"When leaders have room to grow, their teams can grow with them...", ty:"Image", r:4, c:0, rp:0},
      {t:"An employee swipes a company card. Another pays out of pocket. Someone submits...", ty:"Article/Link", r:15, c:0, rp:6},
      {t:"OpenAI published a story last week about how our team at Stampli used ChatGPT for...", ty:"Article/Link", r:18, c:2, rp:3},
      {t:"Answering a good finance question shouldn't require a costly project. Stampli Deep...", ty:"Video", r:44, c:7, rp:10},
      {t:"Month-end problems rarely begin at month-end. For Advance...", ty:"Image", r:17, c:0, rp:7},
      {t:"Business leaders always have questions. They just don't ask all of them because...", ty:"Video", r:47, c:5, rp:5},
      {t:"In finance, efficiency only matters if you can improve it without giving up control...", ty:"Article/Link", r:4, c:0, rp:2},
      {t:"Anyone who's launched a product knows the hard part isn't just one thing. When we...", ty:"Article/Link", r:26, c:2, rp:13},
      {t:"At Quincy Recycle, connecting Procurement and AP brought clarity to daily work and...", ty:"Image", r:25, c:0, rp:7},
      {t:"An invoice in manufacturing is rarely just that. There's usually a PO, a receipt, a...", ty:"Article/Link", r:3, c:0, rp:0},
      {t:"Finance teams don't run out of good questions. They run out of practical ways to get...", ty:"Document/carousel", r:32, c:0, rp:12},
      {t:"\"It's allowed basically a one-person team to do the work of a team of four or five.\"...", ty:"Video", r:0, c:0, rp:0},
      {t:"Finance teams don't run out of useful questions. They run out of practical ways to...", ty:"Article/Link", r:22, c:1, rp:6},
      {t:"Every vendor relationship carries a set of important commitments. For business...", ty:"Article/Link", r:12, c:0, rp:4},
      {t:"From 10 locations to more than 50, America's Group built a finance operation...", ty:"Article/Link", r:19, c:0, rp:8},
      {t:"71 locations. 1,000+ monthly invoices. A two-person AP team. For Advance Financial,...", ty:"Article/Link", r:14, c:0, rp:1},
      {t:"We had a great time at the Nashville career fair meeting people excited about the...", ty:"Image", r:44, c:1, rp:5},
      {t:"Procure-to-pay breaks down fast when teams work across disconnected tools. Stampli...", ty:"Article/Link", r:11, c:0, rp:5},
      {t:"I spent ten years as an accountant before I ever touched marketing. So when OpenAI...", ty:"Video", r:63, c:3, rp:5},
      {t:"We're about to see the death of the dashboard. Here's why they'll get replaced by...", ty:"Image", r:83, c:8, rp:23},
      {t:"Finance leaders do not need a lesson in prompting. They need better data to prompt...", ty:"Article/Link", r:6, c:0, rp:1},
      {t:"New software shouldn't take years to deliver value. Stampli has the fastest...", ty:"Image", r:36, c:1, rp:14},
      {t:"Ask your agentic financial analyst anything. Get consultant-grade intelligence about...", ty:"Video", r:39, c:0, rp:22},
      {t:"What changes when finance teams can analyze data in ways that used to be slow,...", ty:"Article/Link", r:13, c:0, rp:1},
      {t:"Accounts Payable is where Procure-to-Pay either works or breaks. In G2's Summer 2026...", ty:"Article/Link", r:18, c:0, rp:6},
      {t:"Vendor renewal coming up? A lot can change since the last contract. Spend patterns,...", ty:"Article/Link", r:12, c:1, rp:4},
      {t:"\"Those little clicks add up. When you're doing that a thousand times a day, it...", ty:"Video", r:25, c:0, rp:10},
      {t:"Strong customer feedback on real value for finance teams to create one connected P2P...", ty:"Article/Link", r:37, c:1, rp:16},
      {t:"Finance teams don't run out of useful questions. They run out of practical ways to...", ty:"Article/Link", r:22, c:1, rp:6},
      {t:"NetSuite 3-way matching often breaks on one missing piece: the item receipt. When...", ty:"Article/Link", r:9, c:0, rp:2},
      {t:"ACH risks don't start at the bank portal. They often start earlier. A vendor bank...", ty:"Article/Link", r:17, c:3, rp:7},
      {t:"Your team is addicted to corporate card swipes and free trials they forget to...", ty:"Image", r:9, c:0, rp:0},
      {t:"Finance professionals paired with the right platform turn complexity into a scalable...", ty:"Image", r:11, c:0, rp:3},
      {t:"Built to scale your business, not your headcount. Stampli's AI performs an average...", ty:"Article/Link", r:25, c:0, rp:11},
      {t:"Saving time at every step of the P2P process with one unified system built for the...", ty:"Video", r:25, c:0, rp:11},
      {t:"Vendor concentration risk is hiding in your AP data. With Stampli Deep Finance, you...", ty:"Article/Link", r:11, c:0, rp:1},
      {t:"Day 1 of #SageFuture in the books. Partner day was fantastic. Got to connect with...", ty:"Image", r:91, c:1, rp:5},
      {t:"The Ollie team went from hours a day leashing wild invoices to just minutes with...", ty:"Video", r:23, c:0, rp:5},
      {t:"Yes... it really is easier than endless approvals hidden in email threads. Not just...", ty:"Video", r:14, c:0, rp:5},
      {t:"Budget variance usually doesn't start with one big decision. It builds quietly...", ty:"Article/Link", r:7, c:0, rp:2},
      {t:"The data moving through finance systems holds a story that teams never see. Stampli...", ty:"Article/Link", r:25, c:1, rp:6},
      {t:"The most valuable signals in finance are buried in places traditional BI can't...", ty:"Video", r:52, c:2, rp:6},
      {t:"We're launching something big: an agentic financial analyst you can ask anything...", ty:"Video", r:148, c:3, rp:21},
      {t:"Stampli Deep Finance transforms raw finance data into executive spend intelligence...", ty:"Article/Link", r:46, c:2, rp:29},
      {t:"Instead of hiring more AP staff with every acquisition, America's Group automated...", ty:"Article/Link", r:14, c:0, rp:6},
      {t:"No matter your ERP, Stampli fits right in. For America's Auto Auction, that's...", ty:"Article/Link", r:17, c:0, rp:9},
      {t:"Market stories become clearer when they show up in operational spend. Josh...", ty:"Video", r:11, c:1, rp:4},
      {t:"Corporate cards don't have to mean losing control of spend. With the right controls,...", ty:"Article/Link", r:17, c:0, rp:5},
      {t:"We're grateful for all our customers. Even more grateful for those who share their...", ty:"Article/Link", r:65, c:0, rp:35},
      {t:"As finance teams look toward 2026, AI is everywhere, but real impact is uneven. In...", ty:"Article/Link", r:40, c:0, rp:7}
    ]}
  ]
};
