/* =========================================================================
   LinkedIn post-engagement data for the Continia competitor dashboard.
   Public engagement on each company's recent posts (reactions / comments /
   reposts). Totals + averages are computed in dashboard.js from these raw
   posts, so the comparison table can never drift from the source.

   Source: Assets/linkedin_post_engagement_report_Aug 31.txt (captured 2026-08-31).
   "t" is the post title (first line of the post, normalized to plain ASCII),
   "ty" is the content type pill. The report lists newest-first per company;
   we keep the 30 most-recent posts each.

   On the tracking list but deliberately excluded (watch, not card - see
   FULL-UPDATE.md): incedo-inc (consulting firm), signup-software (Truvio's
   former brand, already the ExFlow/Truvio card), stripe (payments benchmark).
   ========================================================================= */

window.LI_DATA = {
  source: "LinkedIn public engagement",
  captured: "2026-08-31",
  windowLabel: "up to 30 recent posts each · public engagement",
  companies: [
    { name: "Continia Software", ours: true, posts: [
      {t:"It's about time... we found out who's faster", ty:"Image", r:85, c:0, rp:0},
      {t:"Colleagues, vineyards, and a glass (or two) of wine", ty:"Image", r:80, c:2, rp:0},
      {t:"It's about time you stopped doing these 5 things", ty:"Document/carousel", r:33, c:2, rp:1},
      {t:"12 free features your Business Central setup is missing", ty:"Document/carousel", r:39, c:0, rp:5},
      {t:"We've got room left on the team!", ty:"Document/carousel", r:33, c:0, rp:4},
      {t:"Your e-invoicing data is only as safe as your vendor", ty:"Image", r:27, c:0, rp:3},
      {t:"Every AP automation pitch this year sounds the same...", ty:"Image", r:21, c:0, rp:2},
      {t:"We're back from a great DynamicsCon in Ghana", ty:"Image", r:63, c:2, rp:2},
      {t:"Same Monday, two very different workdays", ty:"Image", r:30, c:0, rp:1},
      {t:"The office is quiet. Why not spend the summer learning?", ty:"Image", r:23, c:0, rp:0},
      {t:"Separate accounts-but it's one relationship", ty:"Image", r:33, c:1, rp:5},
      {t:"More than 1,000 active Continia solutions", ty:"Image", r:119, c:1, rp:8},
      {t:"Submitting expenses just got even easier!", ty:"Document/carousel", r:37, c:5, rp:8},
      {t:"See Continia in action, at your own pace", ty:"Image", r:36, c:1, rp:4},
      {t:"It's about time... for an ice-cream break!", ty:"Image", r:70, c:1, rp:0},
      {t:"Fake invoices don't always look fake", ty:"Image", r:23, c:0, rp:3},
      {t:"Our biggest team meetup yet", ty:"Image", r:243, c:4, rp:6},
      {t:"From a full-time AP person to automation in minutes", ty:"Image", r:23, c:0, rp:3},
      {t:"The Elevate tour continues - this time in Poland!", ty:"Image", r:71, c:1, rp:0},
      {t:"Kicking off Continia Elevate in the UK", ty:"Video", r:53, c:2, rp:1},
      {t:"We're ISO 27001 certified", ty:"Image", r:195, c:2, rp:1},
      {t:"It's about time ... we cycled to work", ty:"Image", r:69, c:1, rp:0},
      {t:"250 Continia-losninger er en god grund til kage", ty:"Image", r:70, c:1, rp:2},
      {t:"Thanks for a great time at DynamicsMinds!", ty:"Image", r:93, c:2, rp:0},
      {t:"Continia is growing - swipe to find your next role", ty:"Document/carousel", r:42, c:0, rp:0},
      {t:"Your BC setup is almost there. Why not upgrade it for free?", ty:"Video", r:34, c:0, rp:4},
      {t:"Continia Elevate comes to Warsaw!", ty:"Image", r:47, c:4, rp:2},
      {t:"That's a wrap on Directions ASIA", ty:"Image", r:59, c:0, rp:0},
      {t:"The Continia Expense App now supports Microsoft Intune", ty:"Image", r:69, c:0, rp:2},
      {t:"Is your Accounts Receivable setup as efficient as it could be?", ty:"Document/carousel", r:39, c:0, rp:0}
    ]},
    { name: "Truvio", posts: [
      {t:"4 minutes versus 17 minutes per invoice.", ty:"Video", r:16, c:0, rp:2},
      {t:"B2B-kunder begynder ikke nodvendigvis deres kobsrejse pa jeres webshop.", ty:"Image", r:10, c:2, rp:0},
      {t:"Invoice capture is only one part of accounts payable automation. What happens when customers also need greater control over approvals, matching", ty:"Image", r:33, c:2, rp:5},
      {t:"One last episode. One last chance to enter!", ty:"Text", r:2, c:0, rp:0},
      {t:"A keynote worth joining us in Aarhus for.", ty:"Image", r:25, c:0, rp:2},
      {t:"Truvio is heading to Columbus for DynamicsCon Regional: Ohio Valley!", ty:"Image", r:20, c:1, rp:2},
      {t:"We're proud to sponsor the 4PS Customer Day 2026!", ty:"Image", r:27, c:3, rp:1},
      {t:"Running, walking and cheering each other on", ty:"Image", r:78, c:0, rp:1},
      {t:"One last conversation before we officially close out summer.", ty:"Image", r:14, c:0, rp:3},
      {t:"AI er allerede ved at aendre den made, B2B-kunder finder, sammenligner og vaelger produkter pa.", ty:"Image", r:14, c:0, rp:1},
      {t:"The Commerce Product Brief is already next week", ty:"Image", r:15, c:0, rp:4},
      {t:"Remember when waiting was just part of the process?", ty:"Text", r:23, c:0, rp:3},
      {t:"Nine steps. Zero manual touchpoints.", ty:"Image", r:15, c:0, rp:3},
      {t:"A little sneak peek at what's coming next to Truvio Talks...", ty:"Image", r:19, c:0, rp:4},
      {t:"Only 2 more days until the next episode of Truvio Talks!", ty:"Text", r:3, c:0, rp:0},
      {t:"When you're in the middle of a complex ERP transformation, a smooth implementation can make a real difference. That was the experience at Blackwoods.", ty:"Image", r:18, c:0, rp:0},
      {t:"Vi glaeder os til at vaere med, nar Computerworld Events saetter fokus pa vejen videre fra Dynamics AX den 25. august i Koge.", ty:"Image", r:22, c:0, rp:1},
      {t:"Hylke Britstra is taking the stage at Directions for Enterprise 2026 in Copenhagen. His session, 'F&O is just a tool'.", ty:"Image", r:27, c:0, rp:2},
      {t:"Summer isn't over yet, and neither is your chance to win!", ty:"Image", r:15, c:0, rp:5},
      {t:"We're excited to share that Truvio is a Gold Sponsor at Days of Knowledge - ANZ 2026, taking place on 3-4 September in Melbourne.", ty:"Image", r:19, c:0, rp:3},
      {t:"(repost) This year I started working for Truvio, currently focusing on the ExFlow AP module in D365FO.", ty:"Image", r:124, c:6, rp:11},
      {t:"Manual payments cost more than money.", ty:"Image", r:25, c:0, rp:5},
      {t:"Less than one month to go until Truvio Commerce Partner Days 2026!", ty:"Image", r:23, c:0, rp:2},
      {t:"Tomorrow, new EU packaging rules begin to apply.", ty:"Image", r:16, c:0, rp:7},
      {t:"This week, we're hosting two APJ Partner Training sessions for D365 F&O partners.", ty:"Image", r:14, c:0, rp:3},
      {t:"Truvio is heading to Directions for Enterprise 2026 in Copenhagen!", ty:"Image", r:52, c:2, rp:2},
      {t:"Summer may be winding down, but there's still time to make your finance operations more resilient.", ty:"Image", r:8, c:0, rp:2},
      {t:"A 4.65/5 score is one thing. Understanding what drives enterprise fit is another. Avanade evaluated Truvio AP Automation.", ty:"Image", r:28, c:0, rp:8},
      {t:"Every quarter brings new improvements across Truvio Commerce.", ty:"Image", r:10, c:0, rp:0},
      {t:"Ready to shorten your order-to-cash cycle?", ty:"Text", r:11, c:0, rp:4}
    ]},
    { name: "Equisys", posts: [
      {t:"Our Implementation Services help Business Central partners deliver faster, smoother Zetadocs projects for their customers with less risk and more pred", ty:"Image", r:3, c:0, rp:3},
      {t:"Manage your documents more effectively, rather than just storing them in a repository. Discover why Business Central customers choose Zetadocs Capture", ty:"Image", r:3, c:0, rp:4},
      {t:"Cut costs without compromising control", ty:"Image", r:4, c:0, rp:2},
      {t:"With Zetadocs, you can drag and drop supporting documents against a journal entry in Business Central. This provides context or justification for a tr", ty:"Image", r:4, c:1, rp:2},
      {t:"Missed our recent webinar? Catch up now!", ty:"Video", r:5, c:0, rp:2},
      {t:"We're just a few hours away from our webinar, 'Discover THE BEST AP Automation Solution for Business Central'!", ty:"Image", r:1, c:0, rp:1},
      {t:"There's less than 24 hours left to register for our webinar - 'Discover THE BEST AP Automation solution for Business Central'", ty:"Image", r:2, c:0, rp:3},
      {t:"Looking for a smarter way to manage employee expenses and ensure compliant claims? Book a demo of Zetadocs Expenses today:", ty:"Image", r:3, c:0, rp:3},
      {t:"Last week, we had a great time sponsoring Directions North America 2026! Thank you to all that stopped by to chat about Zetadocs and those who entered", ty:"Image", r:12, c:0, rp:2},
      {t:"We had an amazing first day at Directions North America and can't wait to see what day two brings! Be sure to stop by our booth (E-32) to say hello an", ty:"Image", r:15, c:0, rp:5},
      {t:"We'll be in Orlando, Florida next week for Directions North America, and we'd love to say hello. Drop by booth E-32 to meet the team, ask questions, a", ty:"Image", r:5, c:0, rp:3},
      {t:"We're headed to Directions in Orlando, Florida in 2 weeks", ty:"Image", r:6, c:0, rp:4},
      {t:"Deliver smarter, not harder!", ty:"Image", r:2, c:0, rp:0},
      {t:"We're delighted to be part of this exciting event that takes an in-depth look at AP Automation options for Microsoft Dynamics 365 Business Central.", ty:"Image", r:3, c:0, rp:1},
      {t:"Zetadocs Expenses offers a smooth expense workflow right out-of-the-box, with minimal training required for both finance teams and the submitters.", ty:"Image", r:4, c:0, rp:1},
      {t:"It's not too late to reserve your space on today's Lunch & Learn event!", ty:"Image", r:3, c:0, rp:5},
      {t:"It's not too late - join a Lunch & Learn event this week to learn how to get even more out of your Zetadocs investment. Book your place now via the li", ty:"Image", r:3, c:0, rp:2},
      {t:"Our Lunch & Learn series starts next week! Are you registered yet? Each session will last around 15 minutes and is designed to demonstrate tricks and", ty:"Image", r:1, c:0, rp:1},
      {t:"Looking forward to being part of this great event!", ty:"Image", r:1, c:0, rp:0},
      {t:"Looking for an expense management solution built for Business Central, ready to go straight away? Look no further than Zetadocs Expenses.", ty:"Image", r:7, c:0, rp:2},
      {t:"Even the most well-written expense policies can prove difficult to enforce across a company. This whitepaper discusses the hurdles finance teams face", ty:"Image", r:7, c:0, rp:4},
      {t:"See how Zetadocs can transform the way you work. Book a demo today to explore any of our AP automation, document management or expense management solu", ty:"Image", r:6, c:0, rp:4},
      {t:"The future of accounts payable is automated. Explore expert perspectives on how AI and accounting technology will drive efficiency, accuracy and bette", ty:"Article/Link", r:2, c:0, rp:0},
      {t:"Zetadocs Delivery helps finance teams spend less time on admin and more time on what really matters. Learn more about how it could help save your team", ty:"Image", r:3, c:0, rp:2},
      {t:"Learn how to build a clear travel and entertainment expenses policy that's easy to consistently enforce in this blog post:", ty:"Image", r:1, c:0, rp:1},
      {t:"Still chasing approvals and fixing errors? AP automation removes bottlenecks, speeds up approvals and helps teams scale without the stress.", ty:"Article/Link", r:0, c:0, rp:0},
      {t:"Many employees feel unsure about what they can expense, even if upper management think they have a clear expense policy. Solutions like Zetadocs Expen", ty:"Image", r:1, c:0, rp:1},
      {t:"AI in ERP is accelerating fast, and ISVs are leading the way with practical, real-world innovations. Read this article to find out why AI-driven ISV s", ty:"Article/Link", r:3, c:0, rp:2},
      {t:"This month we're celebrating 15 years of the Equisys blog! Here's some of the highlights from along the way", ty:"Document/carousel", r:3, c:0, rp:1},
      {t:"Accounting teams in the manufacturing industry (and beyond) are facing challenges with manual AP workflows. Check out this article on why automating A", ty:"Article/Link", r:1, c:0, rp:0}
    ]},
    { name: "Medius", posts: [
      {t:"September is a good month to sort out AP.", ty:"Document/carousel", r:4, c:0, rp:0},
      {t:"Not sure which AP automation features actually matter, and which are just on the checklist for show?", ty:"Image", r:7, c:0, rp:1},
      {t:"Medius' Financial Census 2026 is officially here.", ty:"Document/carousel", r:34, c:0, rp:10},
      {t:"Join the Medius team at the upcoming inPOWER User Conference, taking place September 14-17 in Pewaukee, Wisconsin.", ty:"Image", r:10, c:1, rp:0},
      {t:"What better way to close out the week than with a new edition of MediusExplains? Today, we're discussing the 5 signs your AP process is costing you sp", ty:"Document/carousel", r:8, c:0, rp:2},
      {t:"Mark your calendars! Our Top Tips in Action live interactive webinar is coming up on September 9, 10:00 - 10:30 AM ET.", ty:"Image", r:11, c:0, rp:4},
      {t:"Invoices processed in one day.", ty:"Image", r:21, c:0, rp:6},
      {t:"What are the most common causes of late payments in B2B?", ty:"Article/Link", r:6, c:0, rp:0},
      {t:"Medius will be at JDE INFOCUS 2026, taking place September 21-23 in Denver, Colorado. This three-day event will join the JD Edwards community for hand", ty:"Image", r:14, c:0, rp:0},
      {t:"A failed invoice match in manufacturing isn't just an AP problem.", ty:"Article/Link", r:7, c:0, rp:2},
      {t:"58% of AP teams are already using or piloting AI. The other 42% are watching the gap widen.", ty:"Image", r:11, c:0, rp:1},
      {t:"Join us on August 26 for our Explore Medius: Compliance & E-invoicing live webinar.", ty:"Image", r:66, c:0, rp:5},
      {t:"Duplicate payments in retail don't usually look like duplicates.", ty:"Article/Link", r:6, c:0, rp:0},
      {t:"Join us on August 20 for our Medius Momentum: Q3 2026 Product Update, a live webinar featuring our own Graeme Chard, SVP, Product Marketing, as he pro", ty:"Image", r:34, c:2, rp:4},
      {t:"Most enterprise finance teams aren't waiting on budget to modernize AP. They're waiting on IT. And IT is waiting on the ERP.", ty:"Image", r:4, c:1, rp:0},
      {t:"Great Northern Equipment: small team, big efficiency gains", ty:"Image", r:32, c:0, rp:10},
      {t:"We had a great time this week at the Microsoft AI Business Solutions Partner Executive Summit.", ty:"Image", r:63, c:0, rp:1},
      {t:"AP fraud doesn't announce itself. It hides in duplicate invoices and last-minute bank account changes.", ty:"Article/Link", r:6, c:0, rp:0},
      {t:"The accounts payable process covers a lot of ground: purchase orders, invoice capture, three-way matching, approvals, payment scheduling, and record-k", ty:"Article/Link", r:13, c:0, rp:3},
      {t:"Still chasing invoice approvals and manually keying payments? There's a live demo for that.", ty:"Image", r:11, c:0, rp:4},
      {t:"Innovation meets efficiency: Marshalls plc's AP automation journey", ty:"Image", r:17, c:0, rp:3},
      {t:"We're excited to return with a new edition of our MediusAsks series. This series invites our team of experts at Medius to share their insights on the", ty:"Video", r:20, c:0, rp:1},
      {t:"The industry average for invoice cycle time is 8.2 days.", ty:"Article/Link", r:11, c:0, rp:1},
      {t:"In the food and beverage industry, fast-moving operations require real-time invoicing and tight delivery schedules.", ty:"Image", r:7, c:0, rp:0},
      {t:"Choosing AP solutions can be as complex and confusing as managing AP itself, but we think analysis like this from Gartner can help clarify which solu", ty:"Image", r:34, c:0, rp:6},
      {t:"You're already running AP on Medius. Invoices are moving, approvals are flowing, payments are going out.", ty:"Image", r:44, c:0, rp:6},
      {t:"Say goodbye to AP exceptions with intelligent automation", ty:"Image", r:15, c:0, rp:1},
      {t:"The most significant financial leaks in transportation rarely appear on the invoice header. They are buried in the line items-fuel surcharges, demurra", ty:"Image", r:10, c:0, rp:0},
      {t:"Late payments affect most businesses, even those using e-invoicing.", ty:"Image", r:15, c:0, rp:2},
      {t:"Is your payment mix actually working for you - or against you?", ty:"Image", r:13, c:0, rp:2}
    ]},
    { name: "Qvalia", posts: [
      {t:"E-invoicing mandates are becoming infrastructure decisions.", ty:"Image", r:5, c:0, rp:1},
      {t:"The new Billentis report on the global e-invoicing market is here.", ty:"Image", r:8, c:2, rp:0},
      {t:"Slovakia's eFaktura framework is another important step in Europe's transition toward structured electronic invoicing.", ty:"Image", r:27, c:0, rp:2},
      {t:"Qvalia is now certified for Slovakia e-invoicing under the eFaktura framework.", ty:"Image", r:32, c:1, rp:6},
      {t:"Qvalia's Business Continuity Management System has now been certified against ISO 22301:2019, the international standard for business continuity pl", ty:"Image", r:6, c:0, rp:1},
      {t:"Qvalia is now listed in the Cloud Security Alliance STAR Registry.", ty:"Image", r:8, c:1, rp:0},
      {t:"Qvalia is now available on iPhone and Android.", ty:"Image", r:42, c:5, rp:5},
      {t:"In 2025, we expanded Qvalia's platform across nearly all fronts. Fredrik Forsell highlights the year's product updates - from new APIs to AI capabilit", ty:"Image", r:13, c:1, rp:2},
      {t:"[Peppol for developers] How to get started with Peppol API.", ty:"Image", r:9, c:0, rp:1},
      {t:"Belgium mandates #Peppol e-invoicing for most B2B transactions on January 1, 2026. Our guide covers all you need to know and how to com", ty:"Image", r:9, c:0, rp:1},
      {t:"The 2026 Peppol country guide - full list, status, and coverage map. Learn where #Peppol is available, national connectivity, and more", ty:"Image", r:14, c:0, rp:0},
      {t:"Thank you to everyone who joined today's webinar with Julius Nilsson from Docupath and Henri Taipale on #IDP - Intelligent Document Proces", ty:"Image", r:29, c:3, rp:3},
      {t:"[Upcoming webinar] AI-ready finance with Intelligent Document Processing", ty:"Image", r:25, c:0, rp:7},
      {t:"Great day at Qvalia together with our friends from Amazon Web Services (AWS).", ty:"Image", r:81, c:3, rp:8},
      {t:"Connect is more than digital invoicing. It's your gateway to automation, compliance, and smarter financial management.", ty:"Article/Link", r:4, c:1, rp:0},
      {t:"Introducing Qvalia Connect", ty:"Video", r:18, c:1, rp:2}
    ]},
    { name: "AMC Banking", posts: [
      {t:"What do you learn from 30+ years of working with bank integration?", ty:"Image", r:16, c:1, rp:1},
      {t:"How many systems does your finance team touch just to make a payment?", ty:"Article/Link", r:12, c:1, rp:0},
      {t:"Before summer kicks off, we wanted to share a small milestone from AMC Banking.", ty:"Image", r:13, c:2, rp:2},
      {t:"Your biggest compliance risk might be a process nobody questions anymore", ty:"Article/Link", r:6, c:0, rp:2},
      {t:"Thanks to everybody who showed up for the reception in our new building! We are looking forward to show it once we are done renovating it.", ty:"Image", r:29, c:1, rp:0},
      {t:"You can still register for our reception next week if you would like to swing by and say hi.", ty:"Text", r:0, c:0, rp:0},
      {t:"AMC Banking operates under Service Provider Agreements with selected banks, providing a more structured framework for bank integration and onboarding.", ty:"Text", r:9, c:0, rp:0},
      {t:"AMC is expanding and we are currently looking for a java developer.", ty:"Article/Link", r:12, c:0, rp:3},
      {t:"Still uploading payment files manually?", ty:"Article/Link", r:6, c:0, rp:0},
      {t:"We're moving and we'd love to celebrate with you.", ty:"Text", r:12, c:0, rp:1},
      {t:"The torch has officially been passed", ty:"Image", r:56, c:4, rp:1},
      {t:"Enterprise treasury demands structure, visibility, and control.", ty:"Image", r:7, c:0, rp:0},
      {t:"Bank integration: Myth vs reality", ty:"Video", r:11, c:0, rp:3},
      {t:"The AMC Banking webinar series offers: demos, new features, use cases and Q&A, focused on simplifying cash management in Dynamics 365.", ty:"Video", r:10, c:0, rp:1},
      {t:"(ingen tekst)", ty:"Document/carousel", r:4, c:0, rp:0},
      {t:"ERP bank integration is rarely 'plug-and-play'.", ty:"Image", r:24, c:0, rp:0},
      {t:"We bought The White House... at Frederiksberg.", ty:"Article/Link", r:30, c:3, rp:2},
      {t:"Discover our new app designed to simplify and automate cash management directly inside Microsoft Dynamics 365 Business Central. AMC Banking 365 BC cen", ty:"Video", r:6, c:0, rp:0},
      {t:"You can still sign up for our webinar tomorrow where we take a deep dive into the capabilities of our brand new Business Central app.", ty:"Article/Link", r:4, c:0, rp:0},
      {t:"In this webinar, we'll take you through how AMC Banking's intelligent cash sweeping for Microsoft Dynamics 365 Finance helps you optimize liquidity.", ty:"Video", r:11, c:0, rp:0},
      {t:"In case you have not yet signed up for our treasury extension webinar about cash sweeping, you can still make it.", ty:"Article/Link", r:5, c:0, rp:0},
      {t:"We're excited to team up with Columbus to show how liquidity management can be automated inside Dynamics 365 Finance.", ty:"Image", r:6, c:0, rp:2},
      {t:"Convenience is the key word for our AMC Banking app - giving you the ability to access and approve payments wherever you are from your phone.", ty:"Text", r:8, c:0, rp:0}
    ]},
    { name: "B2Brouter", posts: [
      {t:"J-5 : une facture conforme peut malgre tout echouer si vos donnees clients sont incorrectes.", ty:"Text", r:3, c:0, rp:1},
      {t:"J-7 en France : attendre de voir ce qui se passe n'est plus une strategie.", ty:"Image", r:11, c:2, rp:4},
      {t:"La facturation electronique n'est que la moitie de la reforme. Avez-vous prepare votre e-reporting ?", ty:"Document/carousel", r:3, c:2, rp:1},
      {t:"J-14 avant la reforme : pour les editeurs de logiciels, le dernier moment est deja la.", ty:"Image", r:12, c:7, rp:2},
      {t:"Electronic invoicing is accelerating across Europe, and B2Brouter is growing with it.", ty:"Article/Link", r:5, c:0, rp:0},
      {t:"(repost: Oriol Bausa) Ja no hi ha excuses per adoptar la facturacio electronica, queden molt pocs dies i els que segueixen esperant potser no seran a temps de complir amb l", ty:"Article/Link", r:19, c:1, rp:2},
      {t:"La reforme francaise de la facturation electronique ne concerne pas seulement la France. Elle a aussi un impact sur les flux internationaux.", ty:"Image", r:9, c:0, rp:1},
      {t:"Si la reforme francaise parait simple en septembre, ce ne sera pas parce qu'elle l'est.", ty:"Text", r:0, c:0, rp:0},
      {t:"El otro dia Aleix Gasset se atrevio a explicarnos en un video de dos minutos que es FACe y como funciona.", ty:"Article/Link", r:3, c:0, rp:0},
      {t:"(repost: e-Invoice.app) Partner Announcement: B2Brouter", ty:"Image", r:10, c:2, rp:3},
      {t:"(repost: Oriol Bausa) Le permier Septembre est prochajn!", ty:"Article/Link", r:7, c:1, rp:2},
      {t:"Die E-Rechnung in Deutschland ist bereits Realitat - trotzdem halten sich noch einige Missverstandnisse.", ty:"Document/carousel", r:2, c:0, rp:0},
      {t:"B2Brouter talent stands out in London!", ty:"Image", r:38, c:0, rp:4},
      {t:"Comment bien choisir sa Plateforme Agreee avant l'entree en vigueur de la reforme de la facturation electronique ?", ty:"Document/carousel", r:6, c:0, rp:1},
      {t:"(repost: Oriol Bausa) Verifactu como el primer paso hacia el despliegue de ViDA, creo que es imprescindible impulsar Verifactu para estar listos para la iniciativa europea.", ty:"Article/Link", r:13, c:2, rp:1},
      {t:"SCI, LMNP et facturation electronique : etes-vous vraiment concerne ?", ty:"Article/Link", r:6, c:0, rp:2},
      {t:"Germany's e-invoicing rollout is not just a national compliance update. It is part of a much bigger European shift.", ty:"Text", r:8, c:0, rp:1},
      {t:"Tu ERP puede emitir facturas, pero... puede cumplir con las nuevas obligaciones de la Ley Crea y Crece?", ty:"Document/carousel", r:8, c:0, rp:2},
      {t:"Belgium's B2B e-invoicing mandate is already in force.", ty:"Document/carousel", r:10, c:1, rp:2},
      {t:"La factura electronica B2B en Espana ya no es un proyecto de futuro: el momento de prepararse es ahora.", ty:"Text", r:1, c:0, rp:0},
      {t:"Plateforme Agreee ou Solution Compatible ?", ty:"Image", r:13, c:4, rp:4},
      {t:"Can your software support both XRechnung and ZUGFeRD?", ty:"Image", r:5, c:0, rp:2},
      {t:"VeriFactu no es el unico gran cambio que viene en Espana", ty:"Image", r:0, c:0, rp:0},
      {t:"Tienes que enviar todas tus facturas a la AEAT?", ty:"Document/carousel", r:5, c:0, rp:2},
      {t:"Como puede un ERP incorporar la facturacion electronica sin asumir toda la complejidad tecnica y normativa?", ty:"Article/Link", r:9, c:4, rp:1},
      {t:"In his latest article, Henrik Moller asks a simple question: if we could rebuild the e-invoicing market from scratch today, what would we do different", ty:"Text", r:3, c:0, rp:0},
      {t:"La reforme fiscale francaise ne se limite pas a 'envoyer des factures electroniques'.", ty:"Document/carousel", r:14, c:0, rp:4},
      {t:"Meet our Sales Team", ty:"Document/carousel", r:9, c:0, rp:3},
      {t:"La factura electronica no va solo de enviar una factura en formato digital.", ty:"Document/carousel", r:2, c:0, rp:1},
      {t:"2026 e-invoicing reality check: is your business ready?", ty:"Poll", r:2, c:0, rp:2}
    ]},
    { name: "Dooap", posts: [
      {t:"Dooap Studio has a new home: https://dooapstudio.ai/", ty:"Image", r:8, c:1, rp:6},
      {t:"We're sponsoring Dynamics User Group (DUG) DynamicsCon Regional: Ohio Valley on August 25-26 in Dublin, OH - and our team will be at the Dooap booth t", ty:"Image", r:9, c:1, rp:1},
      {t:"Everyone is talking about AI in finance. Very few are talking about what's actually working.", ty:"Image", r:6, c:1, rp:1},
      {t:"Sharing our story of Dooap Studio live from Dynamic Communities AI Business Applications Partner Executive Summit this morning.", ty:"Video", r:26, c:2, rp:4},
      {t:"Looking forward to sharing more about Dooap Studio this week at AI Business Solutions Partner Executive Summit.", ty:"Video", r:19, c:0, rp:0},
      {t:"We're heading to Copenhagen!", ty:"Image", r:10, c:0, rp:1},
      {t:"Five years in, and she still says it feels new every day.", ty:"Image", r:18, c:1, rp:0},
      {t:"Who is attending Dynamic Communities's AI Business Solutions Partner Executive Summit? Our CEO, Mikko Hytonen, will be chatting with John Siefert abou", ty:"Image", r:30, c:4, rp:1},
      {t:"Every D365 vendor is racing to say 'agentic' right now. Most are still figuring out what that means in practice.", ty:"Image", r:19, c:1, rp:4},
      {t:"Every AP Manager knows this feeling: you spot the fix, but IT has a three-week queue.", ty:"Article/Link", r:11, c:0, rp:3},
      {t:"Last time we said 'something new is coming,' we introduced Dooap Studio - agentic AP automation for D365 Finance.", ty:"Image", r:25, c:0, rp:3},
      {t:"Somewhere right now, an AP manager is refreshing their inbox hoping an approval magically appeared.", ty:"Image", r:18, c:0, rp:2},
      {t:"We are here and you can find the team and table next to registration. Come chat with us about Agentic AP!", ty:"Video", r:24, c:2, rp:0},
      {t:"The Dynamics community is coming to Toronto - and so are we.", ty:"Image", r:16, c:0, rp:1},
      {t:"Excited to introduce our latest Dooap Unleashed: Run With Us - Eftsure!", ty:"Video", r:39, c:2, rp:1},
      {t:"This is what agentic AP automation looks like.", ty:"Video", r:17, c:0, rp:6},
      {t:"Just think of the possibilities with Dooap Studio! Here's one for you.", ty:"Image", r:14, c:0, rp:1},
      {t:"AP automation doesn't stop at the invoice. So why should your tech stack?", ty:"Video", r:71, c:10, rp:3},
      {t:"We saw a clear shift across #DynamicsCon2026 and #DynamicsMinds2026 this year. The conversation is moving from features to how", ty:"Image", r:21, c:0, rp:0},
      {t:"Well, that's a wrap on DynamicsMinds. The Dooap team is heading back through time and space.", ty:"Image", r:70, c:4, rp:0},
      {t:"Great conversations. Great community.", ty:"Video", r:9, c:1, rp:0},
      {t:"Set up and ready for 'Herd your AP with AI Agents', in Sunset on level 11. Come join us to see agents at work collecting, herding, and making AP happe", ty:"Image", r:28, c:2, rp:3},
      {t:"We're heading to #DynamicsMinds2026 and looking forward to being back with the community.", ty:"Image", r:30, c:0, rp:1},
      {t:"The biggest problem in finance isn't the system. It's that nobody trusts it.", ty:"Video", r:21, c:3, rp:1},
      {t:"Transform your AP process with automation built for Dynamics 365 Finance. Capture invoices, automate approvals, and match POs seamlessly.", ty:"Article/Link", r:15, c:0, rp:0},
      {t:"Sam Bush live here in Helsinki. The Dooap team is gearing up for DynamicsMinds next week and we have a status update.", ty:"Video", r:66, c:4, rp:0},
      {t:"What does AI literacy actually look like for a Dynamics 365 Finance team in 2026?", ty:"Article/Link", r:10, c:0, rp:1},
      {t:"Love spending time with our partners all year around. At Dynamics User Group (DUG) with so many!", ty:"Video", r:9, c:0, rp:2},
      {t:"With AP you have a lot of balls in the air at all times, let Dooap help you herd them with AI!", ty:"Image", r:57, c:1, rp:2},
      {t:"Run AP with AI agents. Not manual work.", ty:"Video", r:46, c:6, rp:8}
    ]},
    { name: "Yavrio", posts: [
      {t:"The Yavrio team is already counting down the days till Directions for Enterprise 2026!", ty:"Image", r:24, c:0, rp:0},
      {t:"Our team just touched down in Ohio and we can't wait to meet with our partners and clients at the Dynamics User Group (DUG) DynamicsCon Regional event", ty:"Image", r:27, c:4, rp:0},
      {t:"This week we've been celebrating the return of Samantha Felling to our USA partner team!", ty:"Image", r:29, c:2, rp:1},
      {t:"More than 5 billion Direct Debit payments run through the UK's Bacs network every year.", ty:"Image", r:31, c:2, rp:2},
      {t:"What does success actually look like when banking is fully integrated into the ERP?", ty:"Video", r:35, c:2, rp:2},
      {t:"Yavrio x Wenalyze", ty:"Image", r:21, c:2, rp:0},
      {t:"What a day", ty:"Image", r:77, c:11, rp:1},
      {t:"Meet Phillip Dawson, our VP Sales & Partnerships!", ty:"Image", r:64, c:8, rp:0},
      {t:"Microsoft's Tier 1 ERP now has modern bank connectivity, embedded payments and treasury available!", ty:"Image", r:40, c:5, rp:0},
      {t:"Four years ago, we launched Yavrio Banking and set out on a mission to create a way for businesses to connect their banks to their ERP and automate re", ty:"Image", r:104, c:26, rp:6},
      {t:"A brilliant afternoon at Fortnum & Mason, bringing together senior retail leaders for an exclusive roundtable with Microsoft.", ty:"Image", r:72, c:7, rp:3},
      {t:"This summer we're opening up our London Paddington office for the first ever Yavrio Open House event!", ty:"Image", r:49, c:8, rp:5},
      {t:"We're excited to welcome Samuel Price as a Sales Consultant as we continue expanding our team in North America!", ty:"Image", r:49, c:9, rp:1},
      {t:"We're excited to be hosting an exclusive roundtable with Microsoft and iLink Digital, designed for retail leaders.", ty:"Image", r:32, c:3, rp:0},
      {t:"We have loved having summer interns at Yavrio this year!", ty:"Image", r:76, c:3, rp:0},
      {t:"8-10 days. That's the average close when statements are still pulled manually.", ty:"Document/carousel", r:13, c:1, rp:1},
      {t:"Meet our Head of UK Sales, Charlotte Huang!", ty:"Image", r:176, c:5, rp:0},
      {t:"A big couple of weeks for the Yavrio team", ty:"Image", r:84, c:1, rp:0},
      {t:"Cards on the Table.", ty:"Image", r:49, c:11, rp:2},
      {t:"We're delighted to announce our partnership with Sabre Limited as adoption of modern bank connectivity and ERP-embedded payments continues to grow.", ty:"Image", r:35, c:6, rp:0},
      {t:"260+ hours a year. That's what manual bank reconciliation costs you per person before Dynamics 365 even starts matching.", ty:"Image", r:17, c:1, rp:1},
      {t:"For finance teams still importing bank statements by CSV into Microsoft Dynamics 365 Business Central, here are 5 things that tend to go wrong.", ty:"Document/carousel", r:15, c:0, rp:1},
      {t:"We are live now with Western Computer for our joint session on banking in Microsoft Dynamics 365 Business Central.", ty:"Text", r:9, c:0, rp:0},
      {t:"Meet our amazing North America Sales Director, Joshua Wilkinson!!", ty:"Image", r:61, c:6, rp:1},
      {t:"Only 18% of finance teams close their books in three days or less. The rest are still downloading bank statements by hand.", ty:"Image", r:17, c:1, rp:1},
      {t:"Still moving bank data into your finance system one CSV at a time? It may be time for an upgrade.", ty:"Video", r:27, c:0, rp:1},
      {t:"The payment is accepted. But is the finance work actually done?", ty:"Image", r:48, c:1, rp:0},
      {t:"What a 2026 Yavrio is having so far!", ty:"Image", r:110, c:9, rp:0},
      {t:"DynamicsMinds 2026 is done and what a week it's been", ty:"Image", r:108, c:5, rp:0},
      {t:"Finance teams BEFORE vs AFTER Yavrio", ty:"Video", r:48, c:5, rp:0}
    ]},
    { name: "Rillion", posts: [
      {t:"(repost: CFO Alliance) 68% of finance teams use AI every day.", ty:"Image", r:23, c:1, rp:2},
      {t:"Don't miss the LinkedIn Live we're hosting today", ty:"Image", r:14, c:1, rp:0},
      {t:"Launch day", ty:"Image", r:24, c:6, rp:1},
      {t:"2029.", ty:"Video", r:12, c:2, rp:0},
      {t:"Are you a finance bro? Sorry, we meant pro!", ty:"Video", r:25, c:1, rp:3},
      {t:"250 U.S. CFOs told us what they really think about AI. Now we're bringing the debate into the studio.", ty:"Image", r:14, c:0, rp:4},
      {t:"Dry run mode: ON", ty:"Video", r:29, c:3, rp:6},
      {t:"Is there a gap between how ready finance leaders think they are for AI and what the operational reality actually shows?", ty:"Video", r:24, c:3, rp:4},
      {t:"The Finance AI Illusion", ty:"Image", r:24, c:3, rp:8},
      {t:"250 US finance leaders told us how they're using AI.", ty:"Document/carousel", r:19, c:2, rp:10},
      {t:"Have you seen the latest OnlyCFO newsletter?", ty:"Image", r:14, c:3, rp:4},
      {t:"Another G2 badge drop we're extremely proud to be part of.", ty:"Video", r:35, c:4, rp:7},
      {t:"'I love my Excel sheets.'", ty:"Video", r:21, c:0, rp:2},
      {t:"(repost: Frida Ahrenby) This is me and Rosanna asking uncomfortable questions to finance leaders across the US and EMEA during the spring!", ty:"Video", r:29, c:5, rp:1},
      {t:"Finance teams aren't slow to adopt AI, we just don't have the luxury of experimenting like other departments.", ty:"Video", r:16, c:1, rp:1},
      {t:"The ERP you choose today can either accelerate your next 10 years... or slow them down tremendously", ty:"Video", r:11, c:0, rp:2},
      {t:"If your finance team only talks to finance, you're leaving value on the table.", ty:"Video", r:12, c:1, rp:1},
      {t:"If AI is already part of your team's daily workflow... this poll probably isn't for you.", ty:"Poll", r:6, c:0, rp:3},
      {t:"AP teams, here's your mid-vacation reminder", ty:"Document/carousel", r:8, c:0, rp:1},
      {t:"Nail your ERP and CRM and you're 90% there - that used to be the rule for finance leaders... not so much anymore", ty:"Video", r:8, c:1, rp:0},
      {t:"Happy Stockholm Pride !", ty:"Image", r:50, c:0, rp:3},
      {t:"Many finance leaders worry AI will make mistakes they can't track. Rasmus Areskoug, CEO and co-founder of Paraglide AI, says that fear is a misconception.", ty:"Text", r:13, c:2, rp:0},
      {t:"What's the best place to start with AI in finance? The small yes/no decisions you're already making every day", ty:"Video", r:14, c:2, rp:1},
      {t:"Denmark leads AI adoption in the Nordics. Sweden lags behind. But Olli Saksa, CFO at Sievo, thinks we're asking the wrong question.", ty:"Text", r:6, c:0, rp:0},
      {t:"80% of finance leaders use AI daily, but only 1 in 5 trust it for strategic decisions.", ty:"Text", r:8, c:3, rp:1},
      {t:"OCR vs AI invoice capture: what's the actual difference for AP automation?", ty:"Document/carousel", r:15, c:1, rp:3},
      {t:"(repost: Rasmus Areskoug) What's possible today wasn't possible 6 months ago. For finance leaders to succeed with AI implementations", ty:"Image", r:45, c:3, rp:4},
      {t:"72% of finance teams still struggle with manual corrections despite investing in AI.", ty:"Text", r:36, c:1, rp:2},
      {t:"AI transformation in finance is more about getting your people onboard than it is about the tech.", ty:"Video", r:31, c:3, rp:5},
      {t:"If you'd told us our favourite team events would be the ones you can track on Strava... we'd probably believe you", ty:"Image", r:19, c:0, rp:0}
    ]},
    { name: "Fidesic", posts: [
      {t:"Like any large financial data migration, you can expect a migration from Dynamics GP to Business Central to create some workflow disruption", ty:"Article/Link", r:2, c:0, rp:0},
      {t:"#LoveFriday #LoveAutomation", ty:"Image", r:0, c:0, rp:0},
      {t:"#MySummitNA", ty:"Image", r:0, c:0, rp:0},
      {t:"How to Spot AP Bottlenecks Before Growth Stalls. Warning signs your AP process won't scale.", ty:"Image", r:1, c:0, rp:0},
      {t:"Payment behavior directly affects cash flow, supplier relationships, and access to credit. About 55% of all B2B invoiced sales in the U.S. are overdue", ty:"Article/Link", r:1, c:0, rp:0},
      {t:"Cash flow is a fact. Profit is an opinion. #WednesdayWisdom #AccountsPayable", ty:"Image", r:1, c:0, rp:0},
      {t:"Thousands of businesses will be moving from Dynamics GP in the coming years. Begin planning your migration now.", ty:"Article/Link", r:2, c:0, rp:0},
      {t:"Did you know 8 days is how long the median finance team spends closing the books each month, according to an APQC benchmarking survey.", ty:"Image", r:1, c:0, rp:0},
      {t:"This post removes some of the fear around GP end of support and offers practical ways to maximize performance of your GP system.", ty:"Article/Link", r:2, c:0, rp:0},
      {t:"Ready to rock 'n' roll in Nashville for Dynamic Communities Summit NA 2026? We're giving away a pair of AirPods Pro.", ty:"Image", r:2, c:0, rp:1},
      {t:"#LoveFriday #LoveAutomation", ty:"Image", r:0, c:0, rp:0},
      {t:"Fidesic has been recognized as a High Performer on G2.", ty:"Article/Link", r:1, c:0, rp:0},
      {t:"'Discipline in accounts payable is discipline in cash flow.' #WednesdayWisdom #APTeam", ty:"Image", r:0, c:0, rp:0},
      {t:"This post covers what BC handles natively for PO matching and AP automation, where the native tools fall short.", ty:"Article/Link", r:0, c:0, rp:0},
      {t:"Is running accounts payable out of Business Central missing something? AP getting in the way of month-end close?", ty:"Article/Link", r:3, c:0, rp:0},
      {t:"It's comin' up quick! Looking forward to seeing everyone in Nashville for #MySummitNA.", ty:"Image", r:6, c:2, rp:1},
      {t:"When you need to update your AP processes, it makes logical sense to test drive a handful of accounts payable solutions before committing to one.", ty:"Article/Link", r:3, c:0, rp:0},
      {t:"Fidesic has been named Best Of AP Automation Tools for Dynamics ERP in 2026 by ERP Software Blog.", ty:"Article/Link", r:7, c:0, rp:1},
      {t:"Remittance vs. Bank Transfer: Key Differences.", ty:"Image", r:0, c:0, rp:0},
      {t:"Fidesic has been named Best Of AP Automation Tools for Dynamics ERP in 2026 by ERP Software Blog. (dublet af #18)", ty:"Article/Link", r:7, c:0, rp:1},
      {t:"'Every invoice tells a story. Make sure yours check out.' #WednesdayWisdom #AP", ty:"Image", r:0, c:0, rp:0},
      {t:"Is a migration off of Dynamics GP impossible for you right now? Here's a list of things you can do to maximize GP performance.", ty:"Image", r:9, c:0, rp:1},
      {t:"Fidesic is the strongest AP automation choice for organizations running Microsoft Dynamics GP or D365 Business Central.", ty:"Article/Link", r:0, c:0, rp:0},
      {t:"In this post we are going to assume that you know the pain points of manual paper processes.", ty:"Article/Link", r:0, c:0, rp:0},
      {t:"The right AP automation software enables small accounting departments to manage multi-location businesses.", ty:"Article/Link", r:2, c:0, rp:0},
      {t:"Still on Dynamics GP? Fidesic has deployable AI agents for your Accounts Payable process.", ty:"Video", r:7, c:3, rp:0},
      {t:"What separates a successful agentic accounting project from one that fails to deliver value is a vendor who can offer human-to-human service.", ty:"Image", r:1, c:0, rp:0},
      {t:"#FunFactFriday ACH is the largest single B2B payment method by transaction value and the fastest-growing.", ty:"Image", r:1, c:0, rp:0},
      {t:"Some strategies sit firmly within AP's direct control: capturing early payment discounts, eliminating late payment penalties", ty:"Image", r:0, c:0, rp:0},
      {t:"A vendor discount captured is margin for which nobody had to sell anything to earn. #WednesdayWisdom", ty:"Image", r:1, c:0, rp:0}
    ]},
    { name: "Tipalti", posts: [
      {t:"The trouble with global growth begins when you add country number 2.", ty:"Video", r:2, c:2, rp:0},
      {t:"Tipalti Expenses automates approvals, reconciliation, and reimbursements to simplify workflows and control business costs.", ty:"Text", r:4, c:0, rp:0},
      {t:"Who enjoys PO matching? It's arduous, leads to bottlenecks, and any matching errors can cascade into serious problems.", ty:"Image", r:12, c:0, rp:1},
      {t:"New Playbook", ty:"Image", r:3, c:1, rp:0},
      {t:"Before he was a product manager, Yacov Gorovoy was a lawyer. He never coded.", ty:"Image", r:34, c:3, rp:0},
      {t:"League One Volleyball (LOVB) felt stuck with their legacy system.", ty:"Document/carousel", r:3, c:1, rp:1},
      {t:"Do you know what a sunny Summer day in Vancouver calls for? A team picnic on the beach!", ty:"Image", r:97, c:8, rp:3},
      {t:"A company needs to pay a supplier in Germany, a creator in Brazil, and a contractor in the Philippines.", ty:"Image", r:3, c:2, rp:1},
      {t:"Great engineering leadership isn't just about technical expertise; it's about creating environments where people can do their best work.", ty:"Image", r:4, c:1, rp:1},
      {t:"Most finance teams using AI today are using it as a faster way to do things they already knew how to do.", ty:"Article/Link", r:11, c:0, rp:0},
      {t:"When Prodege's partner network grew, so did the operational complexity behind every payment.", ty:"Video", r:11, c:1, rp:0},
      {t:"AI is no longer a 'someday' conversation in finance. It's a 'now' conversation.", ty:"Image", r:11, c:0, rp:0},
      {t:"20 weeks of AP work, eliminated. Every year.", ty:"Document/carousel", r:7, c:0, rp:1},
      {t:"In his latest for the Forbes Tech Council, Tipalti CPTO Roby Baruch discusses how AI is transforming product and engineering organizations.", ty:"Article/Link", r:0, c:0, rp:0},
      {t:"New from the Tipalti Team", ty:"Image", r:25, c:4, rp:0},
      {t:"New from the Tipalti Product Team", ty:"Image", r:101, c:5, rp:0},
      {t:"What does it actually take to build financial infrastructure for a company scaling globally?", ty:"Image", r:7, c:0, rp:0},
      {t:"David Fractor, CFO at ImaginAb, has spent seven years building a finance function inside a biotech company.", ty:"Image", r:9, c:0, rp:0},
      {t:"Technology alone won't make finance more scalable.", ty:"Image", r:7, c:0, rp:0},
      {t:"(repost: Chen Amit) Tipalti has officially been named to the Inc. 5000 list for nine consecutive years.", ty:"Image", r:186, c:4, rp:3},
      {t:"We are thrilled to share that Tipalti has been named to the Inc. 5000 list for the ninth consecutive year.", ty:"Image", r:46, c:1, rp:9},
      {t:"Hear directly from finance leaders at AG1, Lantern Community Services, and Lendable on how Tipalti AI agents transform their AP operations.", ty:"Video", r:9, c:0, rp:0},
      {t:"The best finance leaders often bring perspectives that can't be learned from a textbook.", ty:"Image", r:2, c:2, rp:0},
      {t:"Adding a new country doesn't add one new problem. It adds several at once.", ty:"Video", r:8, c:0, rp:1},
      {t:"81% of organizations say their external partner networks are vital to business success.", ty:"Video", r:7, c:0, rp:1},
      {t:"Even the best partner programs lose talent when payments are slow, complicated, or hard to manage.", ty:"Video", r:8, c:1, rp:1},
      {t:"The Tipalti team is heading to Minneapolis for the Dynamics Community Summit Roadshow, and we're proud to be a sponsor!", ty:"Video", r:6, c:0, rp:0},
      {t:"There's a lot of noise around agentic AI right now, but what we're hearing from finance teams is far more practical.", ty:"Image", r:6, c:1, rp:0},
      {t:"The Tipalti C-Suite were in Vancouver last week for their executive QBR.", ty:"Image", r:127, c:3, rp:2},
      {t:"The finance function is being asked to operate at a higher level. The problem is the day-to-day workload hasn't changed to match.", ty:"Video", r:40, c:0, rp:1}
    ]},
    { name: "Stampli", posts: [
      {t:"(repost: Eyal Feldman) Business leaders always have questions. They just don't ask all of them because answering each one can take weeks of work.", ty:"Video", r:38, c:4, rp:5},
      {t:"Answering a good finance question shouldn't require a costly project.", ty:"Video", r:43, c:7, rp:10},
      {t:"(repost: Melad Zahedi OpenAI published a story last week about how our team at Stampli used ChatGPT for Work and Codex to launch Deep Finance.", ty:"Article/Link", r:16, c:2, rp:3},
      {t:"Anyone who's launched a product knows the hard part isn't just one thing.", ty:"Article/Link", r:26, c:2, rp:13},
      {t:"Month-end problems rarely begin at month-end", ty:"Image", r:17, c:0, rp:7},
      {t:"An invoice in manufacturing is rarely just that. There's usually a PO, a receipt, a plant, a cost center, and someone who needs to make a call.", ty:"Article/Link", r:3, c:0, rp:0},
      {t:"At Quincy Recycle, connecting Procurement and AP brought clarity to daily work and more team capacity.", ty:"Image", r:25, c:0, rp:7},
      {t:"Every vendor relationship carries a set of important commitments.", ty:"Article/Link", r:12, c:0, rp:4},
      {t:"From 10 locations to more than 50, America's Group built a finance operation designed to scale with its growth.", ty:"Article/Link", r:18, c:0, rp:8},
      {t:"71 locations. 1,000+ monthly invoices. A two-person AP team.", ty:"Article/Link", r:11, c:0, rp:1},
      {t:"New software shouldn't take years to deliver value.", ty:"Image", r:35, c:1, rp:15},
      {t:"Procure-to-pay breaks down fast when teams work across disconnected tools", ty:"Article/Link", r:11, c:0, rp:5},
      {t:"Finance leaders do not need a lesson in prompting. They need better data to prompt from.", ty:"Article/Link", r:6, c:0, rp:1},
      {t:"(repost: OpenAI for Business 'It's allowed basically a one-person team to do the work of a team of four or five.'", ty:"Video", r:0, c:0, rp:0},
      {t:"(repost: Melad Zahedi) I spent ten years as an accountant before I ever touched marketing.", ty:"Video", r:63, c:3, rp:5},
      {t:"What changes when finance teams can analyze data in ways that used to be slow, manual, or expensive to explore?", ty:"Article/Link", r:13, c:0, rp:1},
      {t:"Finance teams don't run out of good questions. They run out of practical ways to get answers.", ty:"Document/carousel", r:32, c:0, rp:12},
      {t:"Accounts Payable is where Procure-to-Pay either works or breaks.", ty:"Article/Link", r:18, c:0, rp:6},
      {t:"Vendor renewal coming up? A lot can change since the last contract.", ty:"Article/Link", r:12, c:1, rp:4},
      {t:"Strong customer feedback on real value for finance teams to create one connected P2P story.", ty:"Article/Link", r:37, c:1, rp:16},
      {t:"Finance teams don't run out of useful questions. They run out of practical ways to get answers.", ty:"Article/Link", r:22, c:1, rp:6},
      {t:"Strong customer feedback on real value for finance teams to create one connected P2P story. (dublet af #20)", ty:"Article/Link", r:37, c:1, rp:16},
      {t:"Finance teams don't run out of useful questions. (dublet af #21)", ty:"Article/Link", r:22, c:1, rp:6},
      {t:"Market stories become clearer when they show up in operational spend. Josh Constine's CNN segment adds context on SpaceX's IPO.", ty:"Video", r:11, c:1, rp:4},
      {t:"NetSuite 3-way matching often breaks on one missing piece: the item receipt.", ty:"Article/Link", r:9, c:0, rp:2},
      {t:"ACH risks don't start at the bank portal. They often start earlier.", ty:"Article/Link", r:17, c:3, rp:7},
      {t:"Meaningful savings can hide in everyday finance data. For Integra Investments, Deep Finance surfaced insights worth $20K-$30K a year.", ty:"Image", r:32, c:3, rp:10},
      {t:"Built to scale your business, not your headcount.", ty:"Article/Link", r:25, c:0, rp:11},
      {t:"Vendor concentration risk is hiding in your AP data.", ty:"Article/Link", r:11, c:0, rp:1},
      {t:"Day 2 at #SageFuture and the energy is still going strong! Visit us at booth 126.", ty:"Image", r:42, c:1, rp:1}
    ]}
  ]
};
